-- Fixed Oracle table definitions for the 13 missing tables

-- Table: CLASSIFICATION_DECLASSIFY_ON (fixed table name)
CREATE TABLE CLASSIFICATION_DECLASSIFY_ON (
    CLASS_DECLASS_ID NUMBER(18),
    CLASS_DECLASS VARCHAR2(4000),
    AUTH VARCHAR2(15),
    LDDATE DATE,
    CONSTRAINT CLASSIFICATION_DECLASSIFY_ON_PK PRIMARY KEY (CLASS_DECLASS_ID),
    CONSTRAINT CLASS_DECLASS_ON__CD_ID__CK CHECK (class_declass_id > 0)
);

-- Table: CLASSIFICATION_DERIVED_FROM (fixed table name)
CREATE TABLE CLASSIFICATION_DERIVED_FROM (
    CLASS_DERIVED_ID NUMBER(18),
    CLASS_DERIVED VARCHAR2(4000),
    AUTH VARCHAR2(15),
    LDDATE DATE,
    CONSTRAINT CLASSIFICATION_DERIVED_FROM_PK PRIMARY KEY (CLASS_DERIVED_ID),
    CONSTRAINT CLASS_DERIVED_FROM__CD_ID__CK CHECK (class_derived_id > 0)
);

-- Table: CLASSIFICATION_DISSEMINATION (fixed table name)
CREATE TABLE CLASSIFICATION_DISSEMINATION (
    CLASS_DISSEM_ID NUMBER(18),
    CLASS_DISSEM VARCHAR2(64),
    PARAGRAPH_MARK VARCHAR2(16),
    AUTH VARCHAR2(15),
    LDDATE DATE,
    CONSTRAINT CLASSIFICATION_DISSEMINATION_PK PRIMARY KEY (CLASS_DISSEM_ID),
    CONSTRAINT CLASS_DISS__CLASS_DISS_ID__CK CHECK (class_dissem_id > 0)
);

-- Table: FEEDBACK (fixed DESCRIPTION data type)
CREATE TABLE FEEDBACK (
    FEEDBACK_ID NUMBER(18),
    EVID NUMBER(18),
    ORID NUMBER(18),
    EVENT_TIME FLOAT(53),
    TITLE VARCHAR2(64),
    ANALYST VARCHAR2(32),
    ACCOUNT VARCHAR2(15),
    FEEDBACK_ANALYST VARCHAR2(32),
    FEEDBACK_ACCOUNT VARCHAR2(15),
    DESCRIPTION VARCHAR2(4000),
    RESPONSE VARCHAR2(4000),
    AUTHOR VARCHAR2(64),
    MODDATE DATE,
    LDDATE DATE,
    CONSTRAINT FEEDBACK_PK PRIMARY KEY (FEEDBACK_ID),
    CONSTRAINT FEEDBACK__EVENT_TIME__CK CHECK (event_time >= -9999999999.999),
    CONSTRAINT FEEDBACK__EVID__CK CHECK (evid > 0),
    CONSTRAINT FEEDBACK__FEEDBACK_ID__CK CHECK (feedback_id > 0),
    CONSTRAINT FEEDBACK__ORID__CK CHECK (orid > 0)
);

-- Table: FEEDBACK_SCREENSHOTS (fixed SCREENSHOT data type)
CREATE TABLE FEEDBACK_SCREENSHOTS (
    FBSCREENSHOT_ID NUMBER(18),
    FEEDBACK_ID NUMBER(18),
    TITLE VARCHAR2(64),
    DESCRIPTION VARCHAR2(4000),
    SCREENSHOT BLOB,
    TYPE VARCHAR2(10),
    AUTHOR VARCHAR2(64),
    MODDATE DATE,
    LDDATE DATE,
    CONSTRAINT FEEDBACK_SCREENSHOTS_PK PRIMARY KEY (FBSCREENSHOT_ID),
    CONSTRAINT FEEDBACK_SS__FBSS_ID__CK CHECK (fbscreenshot_id > 0),
    CONSTRAINT FEEDBACK_SS__FEEDBACK_ID__CK CHECK (feedback_id > 0),
    CONSTRAINT FEEDBACK_SS__TYPE__CK CHECK (type IN ('png', 'PNG'))
);

-- Table: FILTER (fixed COMPOUND_FILTER data type)
CREATE TABLE FILTER (
    FILTERID NUMBER(18),
    COMPOUND_FILTER VARCHAR2(1),
    FILTER_METHOD VARCHAR2(2),
    FILTER_STRING VARCHAR2(2000),
    FILTER_HASH VARCHAR2(2000),
    LDDATE DATE,
    CONSTRAINT FILTER_PK PRIMARY KEY (FILTERID),
    CONSTRAINT FILTER__COMPOUND_FILTER__CK CHECK (compound_filter IN ('y','n')),
    CONSTRAINT FILTER__FILTERID__CK CHECK (filterid > 0),
    CONSTRAINT FILTER__FILT_METH__CK CHECK (filter_method IN ('A','B','C','F','G','N','O','U','W'))
);

-- Table: FILTER_GROUP (fixed CHILD_FUNCTION data type)
CREATE TABLE FILTER_GROUP (
    PARENT_FILTERID NUMBER(18),
    CHILD_FILTERID NUMBER(18),
    CHILD_SEQUENCE NUMBER(9),
    CHILD_FUNCTION VARCHAR2(1),
    LDDATE DATE,
    CONSTRAINT FILTER_GROUP_PK PRIMARY KEY (CHILD_FILTERID),
    CONSTRAINT FILTER_GROUP__CHILD_FUNCT__CK CHECK (child_function IN ('f','c')),
    CONSTRAINT FILTER_GROUP__CHILD_SEQ__CK CHECK (child_sequence > 0),
    CONSTRAINT FILTER_GROUP__CHI_FILTERID__CK CHECK (child_filterid > 0),
    CONSTRAINT FILTER_GROUP__PAR_FILTERID__CK CHECK (parent_filterid > 0)
);

-- Table: ORIGIN_SDO (fixed geometry column data types - using VARCHAR2 as placeholder)
CREATE TABLE ORIGIN_SDO (
    ORID NUMBER(18),
    LATLON_GEOM VARCHAR2(4000),
    COV_ELLIPSE_GEOM VARCHAR2(4000),
    CONF_ELLIPSE_GEOM VARCHAR2(4000),
    CONSTRAINT ORIGIN_SDO_PK PRIMARY KEY (ORID),
    CONSTRAINT ORIGIN_SDO__ORID__CK CHECK (orid > 0)
);

-- Table: SADO_PDF_REPORTS (fixed REPORT data type)
CREATE TABLE SADO_PDF_REPORTS (
    SADO_PDF_REPORT_ID NUMBER(18),
    REPORT_ID NUMBER(18),
    REPORT BLOB,
    AUTHOR VARCHAR2(64),
    MODDATE DATE,
    LDDATE DATE,
    CONSTRAINT SADO_PDF_REPORTS_PK PRIMARY KEY (SADO_PDF_REPORT_ID),
    CONSTRAINT SADO_PDF_RPTS__REPORT_ID__CK CHECK (report_id > 0),
    CONSTRAINT SADO_PDF_RPTS__SPR_ID__CK CHECK (sado_pdf_report_id > 0)
);

-- Table: SADO_REPORT (fixed DESCRIPTION data type)
CREATE TABLE SADO_REPORT (
    REPORT_ID NUMBER(18),
    EVID NUMBER(18),
    ORID NUMBER(18),
    GRN NUMBER(8),
    EVENT_TIME FLOAT(53),
    TITLE VARCHAR2(64),
    ANALYST VARCHAR2(32),
    ACCOUNT VARCHAR2(15),
    DESCRIPTION VARCHAR2(4000),
    CLASSIFICATION VARCHAR2(256),
    TTGE VARCHAR2(1),
    SADO_RELEASED VARCHAR2(1),
    ALERT_MANAGER_CALLED VARCHAR2(1),
    EXERCISE VARCHAR2(1),
    EMAIL_TYPE VARCHAR2(32),
    ALERT_MANAGER VARCHAR2(64),
    YIELD_CALCULATOR_REGION_SELECT VARCHAR2(64),
    FINAL_DETERMINATION VARCHAR2(32),
    MAG_MAGTYPE VARCHAR2(32),
    OVERBURDEN_SET VARCHAR2(1),
    OVERBURDEN FLOAT(24),
    COMMENTS VARCHAR2(4000),
    ECM_DETERMINATION VARCHAR2(32),
    AUTHOR VARCHAR2(64),
    MODDATE DATE,
    LDDATE DATE,
    CONSTRAINT SADO_REPORT_PK PRIMARY KEY (REPORT_ID),
    CONSTRAINT SADO_REPORT__ALRT_MGR_CALL__CK CHECK (alert_manager_called IN('N','Y','-')),
    CONSTRAINT SADO_REPORT__EMAIL_TYPE__CK CHECK (email_type IN ( 'Code 0', 'Code 1', 'Code 2' )),
    CONSTRAINT SADO_REPORT__EVENT_TIME__CK CHECK (event_time >= -9999999999.999),
    CONSTRAINT SADO_REPORT__EVID__CK CHECK (evid > 0),
    CONSTRAINT SADO_REPORT__EXERCISE__CK CHECK (exercise IN('N','Y','-')),
    CONSTRAINT SADO_REPORT__FINAL_DETERM__CK CHECK (final_determination IN('Indeterminate','Earthquake','Explosion','Not Applicable' )),
    CONSTRAINT SADO_REPORT__GRN__CK CHECK ((grn >= 1 AND grn <= 729) OR grn = -1),
    CONSTRAINT SADO_REPORT__ORID__CK CHECK (orid > 0),
    CONSTRAINT SADO_REPORT__OVERBURDEN__CK CHECK ((overburden >= 20.0 AND overburden <= 1000.0) OR overburden = -1.0),
    CONSTRAINT SADO_REPORT__OVERBURDN_SET__CK CHECK (overburden_set IN('N','Y')),
    CONSTRAINT SADO_REPORT__REPORT_ID__CK CHECK (report_id > 0),
    CONSTRAINT SADO_REPORT__SADO_RELEASED__CK CHECK (sado_released IN('N','Y','-')),
    CONSTRAINT SADO_REPORT__TTGE__CK CHECK (ttge IN('N','Y','-'))
);

-- Table: SADO_SCREENSHOTS (fixed SCREENSHOT data type)
CREATE TABLE SADO_SCREENSHOTS (
    SADO_SCREENSHOT_ID NUMBER(18),
    REPORT_ID NUMBER(18),
    SCREENSHOT BLOB,
    TYPE VARCHAR2(10),
    AUTHOR VARCHAR2(64),
    MODDATE DATE,
    LDDATE DATE,
    CONSTRAINT SADO_SCREENSHOTS_PK PRIMARY KEY (SADO_SCREENSHOT_ID),
    CONSTRAINT SADO_SS__REPORT_ID__CK CHECK (report_id > 0),
    CONSTRAINT SADO_SS__SADO_SS_ID__CK CHECK (sado_screenshot_id > 0),
    CONSTRAINT SADO_SS__TYPE__CK CHECK (type IN ('png', 'PNG'))
);

-- Table: SADO_STATE_CATEGORIES (fixed DESCRIPTION data type)
CREATE TABLE SADO_STATE_CATEGORIES (
    SADO_STATE_CATEGORY_ID NUMBER(18),
    TITLE VARCHAR2(64),
    DESCRIPTION VARCHAR2(4000),
    AUTHOR VARCHAR2(64),
    MODDATE DATE,
    LDDATE DATE,
    CONSTRAINT SADO_STATE_CATEGORIES_PK PRIMARY KEY (SADO_STATE_CATEGORY_ID),
    CONSTRAINT SADO_ST_CAT__SSC_ID__CK CHECK (sado_state_category_id > 0)
);

-- Table: WFACTIVITY (fixed MAX_ENDTIME precision)
CREATE TABLE WFACTIVITY (
    CLASS VARCHAR2(16),
    NAME VARCHAR2(20),
    TIME FLOAT(53),
    DURATION FLOAT(24),
    MIN_TIME FLOAT(53),
    MAX_ENDTIME FLOAT(53),
    MODDATE DATE,
    LDDATE DATE,
    CONSTRAINT WFACTIVITY_PK PRIMARY KEY (TIME),
    CONSTRAINT WFACTIVITY__DURATION__CK CHECK (duration > 0.0 OR duration = -1.0),
    CONSTRAINT WFACTIVITY__MAX_ENDTIME__CK CHECK (max_endtime > -9999999999.999),
    CONSTRAINT WFACTIVITY__MIN_TIME__CK CHECK (min_time > -9999999999.999),
    CONSTRAINT WFACTIVITY__TIME__CK CHECK (time >= -9999999999.999)
);