#!/bin/bash

# Deploy SchemaSpy Documentation to AWS S3
# Professional database documentation with relationship diagrams and interactive features

set -e

echo "🚀 Deploying SchemaSpy USNDC Documentation to AWS..."

# Generate unique bucket name
BUCKET_NAME="usndc-schemaspy-docs-$(date +%s)"
REGION="us-east-1"
SOURCE_DIR="usndc_schemaspy_docs"

echo "📦 Creating S3 bucket: $BUCKET_NAME"
aws s3 mb s3://$BUCKET_NAME --region $REGION

echo "🌐 Configuring static website hosting..."
aws s3 website s3://$BUCKET_NAME --index-document index.html --error-document index.html

echo "🔓 Making bucket publicly accessible..."
aws s3api put-public-access-block --bucket $BUCKET_NAME --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"

# Create public read policy
cat > schemaspy-bucket-policy.json << EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::$BUCKET_NAME/*"
        }
    ]
}
EOF

echo "📋 Applying public read policy..."
aws s3api put-bucket-policy --bucket $BUCKET_NAME --policy file://schemaspy-bucket-policy.json

echo "📤 Uploading SchemaSpy documentation files..."

# Upload HTML files
aws s3 sync $SOURCE_DIR/ s3://$BUCKET_NAME/ \
    --exclude "*.txt" \
    --include "*.html" \
    --content-type "text/html" \
    --cache-control "no-cache"

# Upload CSS files  
aws s3 sync $SOURCE_DIR/ s3://$BUCKET_NAME/ \
    --exclude "*" \
    --include "*.css" \
    --content-type "text/css" \
    --cache-control "max-age=86400"

# Upload JavaScript files
aws s3 sync $SOURCE_DIR/ s3://$BUCKET_NAME/ \
    --exclude "*" \
    --include "*.js" \
    --content-type "application/javascript" \
    --cache-control "max-age=86400"

# Upload images and other assets
aws s3 sync $SOURCE_DIR/ s3://$BUCKET_NAME/ \
    --exclude "*.html" \
    --exclude "*.css" \
    --exclude "*.js" \
    --cache-control "max-age=604800"

# Upload text files
aws s3 sync $SOURCE_DIR/ s3://$BUCKET_NAME/ \
    --exclude "*" \
    --include "*.txt" \
    --content-type "text/plain"

# Upload XML file
aws s3 sync $SOURCE_DIR/ s3://$BUCKET_NAME/ \
    --exclude "*" \
    --include "*.xml" \
    --content-type "application/xml"

WEBSITE_URL="http://$BUCKET_NAME.s3-website-$REGION.amazonaws.com"

echo ""
echo "✅ SchemaSpy Documentation Deployment Complete!"
echo ""
echo "🌐 Your USNDC SchemaSpy Documentation URLs:"
echo "   Main Documentation: $WEBSITE_URL"
echo "   Tables Overview: $WEBSITE_URL/index.html"
echo "   Relationships: $WEBSITE_URL/relationships.html"
echo "   Constraints: $WEBSITE_URL/constraints.html"
echo "   Anomalies: $WEBSITE_URL/anomalies.html"
echo "   Orphan Tables: $WEBSITE_URL/orphans.html"
echo ""
echo "📊 SchemaSpy Features Available:"
echo "   ✅ Interactive table browser with search and filtering"
echo "   ✅ Entity relationship diagrams (ER diagrams)"
echo "   ✅ Constraint analysis and validation"
echo "   ✅ Anomaly detection and reporting"
echo "   ✅ Column details with data types and constraints"
echo "   ✅ Foreign key relationship mapping"
echo "   ✅ Index analysis and optimization suggestions"
echo "   ✅ Database statistics and metrics"
echo "   ✅ Professional navigation and UI"
echo ""
echo "🗃️ Database Information:"
echo "   Database: usndc_schema (PostgreSQL 15.8 on AWS RDS)"
echo "   Tables: 16 core seismic analysis tables deployed"
echo "   Schema: USNDC (United States National Data Center)"
echo "   Purpose: Global seismic monitoring and earthquake analysis"
echo ""

# Save deployment info
cat > schemaspy-deployment-info.txt << EOF
SchemaSpy USNDC Documentation Deployment
========================================

Bucket: $BUCKET_NAME
Region: $REGION
Website URL: $WEBSITE_URL

Key URLs:
- Main Page: $WEBSITE_URL/index.html
- Relationships: $WEBSITE_URL/relationships.html
- Constraints: $WEBSITE_URL/constraints.html
- Anomalies: $WEBSITE_URL/anomalies.html

Database Details:
- Host: usndc-schema-usndc-schematest3-clone.c0320kayk04f.us-east-1.rds.amazonaws.com
- Port: 5432
- Database: usndc_schema
- Schema: public
- Tables: 16 seismic monitoring tables

Documentation Features:
- Interactive table browser
- ER diagrams and relationships
- Constraint validation
- Anomaly detection
- Professional UI with search and navigation

Deployment Date: $(date)
Generated by: SchemaSpy 6.2.4
EOF

echo "📝 Deployment details saved to schemaspy-deployment-info.txt"
echo ""
echo "🎉 Professional USNDC schema documentation is now live!"

# Clean up
rm -f schemaspy-bucket-policy.json