-- NDC PLUS Schema Migration SQL
-- Generated on 2025-11-01 17:16:14
-- Adds missing columns to existing tables

ALTER TABLE channel_segment ADD COLUMN uid UUID NOT NULL;
ALTER TABLE channel_segment ADD COLUMN hannel_segment_creation_uuid UUID;
ALTER TABLE channel_segment ADD COLUMN eference_id UUID;
ALTER TABLE channel_segment ADD COLUMN reation_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE channel_segment ADD COLUMN han_canonical_name VARCHAR(32);
ALTER TABLE channel_segment ADD COLUMN han_effective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE channel_segment ADD COLUMN ime_series_type VARCHAR(32);
ALTER TABLE channel_segment ADD COLUMN tart_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE channel_segment ADD COLUMN nd_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE channel_segment ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE channel_segment_creation ADD COLUMN uid UUID NOT NULL;
ALTER TABLE channel_segment_creation ADD COLUMN bject TEXT;
ALTER TABLE channel_segment_creation ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE channel_segment_proc_mask_xref ADD COLUMN uid UUID NOT NULL;
ALTER TABLE channel_segment_proc_mask_xref ADD COLUMN hannel_segment_uuid UUID;
ALTER TABLE channel_segment_proc_mask_xref ADD COLUMN rocessing_mask_uuid UUID;
ALTER TABLE channel_segment_proc_mask_xref ADD COLUMN scurrent VARCHAR(1);
ALTER TABLE channel_segment_proc_mask_xref ADD COLUMN oddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE channel_segment_proc_mask_xref ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE channel_segment_waveform ADD COLUMN uid UUID NOT NULL;
ALTER TABLE channel_segment_waveform ADD COLUMN hannel_segment_uuid UUID;
ALTER TABLE channel_segment_waveform ADD COLUMN fid BIGINT;
ALTER TABLE channel_segment_waveform ADD COLUMN scurrent VARCHAR(1);
ALTER TABLE channel_segment_waveform ADD COLUMN oddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE channel_segment_waveform ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE event ADD COLUMN uid UUID NOT NULL;
ALTER TABLE event ADD COLUMN emark_gid UUID;
ALTER TABLE event ADD COLUMN onitoring_organization VARCHAR(32);
ALTER TABLE event ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE event_correlation ADD COLUMN uid UUID NOT NULL;
ALTER TABLE event_correlation ADD COLUMN ource_event_hypothesis_uuid UUID;
ALTER TABLE event_correlation ADD COLUMN imilar_event_hypothesis_uuid UUID;
ALTER TABLE event_correlation ADD COLUMN ource_event_channel_segment_gid UUID;
ALTER TABLE event_correlation ADD COLUMN imilar_event_channel_segment_gid UUID;
ALTER TABLE event_correlation ADD COLUMN ta_name VARCHAR(6);
ALTER TABLE event_correlation ADD COLUMN ta_effective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE event_correlation ADD COLUMN han_list VARCHAR(2000);
ALTER TABLE event_correlation ADD COLUMN ilterid BIGINT;
ALTER TABLE event_correlation ADD COLUMN can_type VARCHAR(32);
ALTER TABLE event_correlation ADD COLUMN can_stages VARCHAR(32);
ALTER TABLE event_correlation ADD COLUMN orrelation_coefficient BINARY_FLOAT;
ALTER TABLE event_correlation ADD COLUMN uthor VARCHAR(32);
ALTER TABLE event_correlation ADD COLUMN tage VARCHAR(32);
ALTER TABLE event_correlation ADD COLUMN scurrent VARCHAR(1);
ALTER TABLE event_correlation ADD COLUMN oddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE event_correlation ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE event_correlation_channel_segment ADD COLUMN uid UUID NOT NULL;
ALTER TABLE event_correlation_channel_segment ADD COLUMN hannel_segment_gid UUID NOT NULL;
ALTER TABLE event_correlation_channel_segment ADD COLUMN han_canonical_name VARCHAR(32);
ALTER TABLE event_correlation_channel_segment ADD COLUMN han_effective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE event_correlation_channel_segment ADD COLUMN ime_series_type VARCHAR(32);
ALTER TABLE event_correlation_channel_segment ADD COLUMN tart_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE event_correlation_channel_segment ADD COLUMN nd_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE event_correlation_channel_segment ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE event_hypothesis ADD COLUMN uid UUID NOT NULL;
ALTER TABLE event_hypothesis ADD COLUMN vent_uuid UUID;
ALTER TABLE event_hypothesis ADD COLUMN referred_location_solution_uuid UUID;
ALTER TABLE event_hypothesis ADD COLUMN emark_gid UUID;
ALTER TABLE event_hypothesis ADD COLUMN eleted VARCHAR(1);
ALTER TABLE event_hypothesis ADD COLUMN ejected VARCHAR(1);
ALTER TABLE event_hypothesis ADD COLUMN referred_by VARCHAR(32);
ALTER TABLE event_hypothesis ADD COLUMN uthor VARCHAR(32);
ALTER TABLE event_hypothesis ADD COLUMN tage VARCHAR(32);
ALTER TABLE event_hypothesis ADD COLUMN scurrent VARCHAR(1);
ALTER TABLE event_hypothesis ADD COLUMN oddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE event_hypothesis ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE event_hypothesis_tag ADD COLUMN uid UUID NOT NULL;
ALTER TABLE event_hypothesis_tag ADD COLUMN vent_hypothesis_uuid UUID NOT NULL;
ALTER TABLE event_hypothesis_tag ADD COLUMN ag VARCHAR(32);
ALTER TABLE event_hypothesis_tag ADD COLUMN uthor VARCHAR(32);
ALTER TABLE event_hypothesis_tag ADD COLUMN tage VARCHAR(32);
ALTER TABLE event_hypothesis_tag ADD COLUMN scurrent VARCHAR(1);
ALTER TABLE event_hypothesis_tag ADD COLUMN oddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE event_hypothesis_tag ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE event_status_info ADD COLUMN uid UUID NOT NULL;
ALTER TABLE event_status_info ADD COLUMN vent_uuid UUID;
ALTER TABLE event_status_info ADD COLUMN vent_status VARCHAR(16);
ALTER TABLE event_status_info ADD COLUMN ctive_analyst_ids VARCHAR(256);
ALTER TABLE event_status_info ADD COLUMN tage VARCHAR(32);
ALTER TABLE event_status_info ADD COLUMN scurrent VARCHAR(1);
ALTER TABLE event_status_info ADD COLUMN oddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE event_status_info ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_measurement_amplitude ADD COLUMN uid UUID NOT NULL;
ALTER TABLE feature_measurement_amplitude ADD COLUMN ig_det_hypo_gid UUID;
ALTER TABLE feature_measurement_amplitude ADD COLUMN easured_channel_segment_uuid UUID;
ALTER TABLE feature_measurement_amplitude ADD COLUMN nalysis_channel_segment_uuid UUID;
ALTER TABLE feature_measurement_amplitude ADD COLUMN ilterid BIGINT;
ALTER TABLE feature_measurement_amplitude ADD COLUMN ilter_usage VARCHAR(32);
ALTER TABLE feature_measurement_amplitude ADD COLUMN han_canonical_name VARCHAR(32);
ALTER TABLE feature_measurement_amplitude ADD COLUMN han_effective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_measurement_amplitude ADD COLUMN easurement_type VARCHAR(20);
ALTER TABLE feature_measurement_amplitude ADD COLUMN mplitude BINARY_FLOAT;
ALTER TABLE feature_measurement_amplitude ADD COLUMN eriod BINARY_FLOAT;
ALTER TABLE feature_measurement_amplitude ADD COLUMN nits VARCHAR(32);
ALTER TABLE feature_measurement_amplitude ADD COLUMN lipped VARCHAR(1);
ALTER TABLE feature_measurement_amplitude ADD COLUMN easurement_window_start_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_measurement_amplitude ADD COLUMN easurement_window_duration BINARY_FLOAT;
ALTER TABLE feature_measurement_amplitude ADD COLUMN easurement_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_measurement_amplitude ADD COLUMN nr BINARY_FLOAT;
ALTER TABLE feature_measurement_amplitude ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_measurement_arrival_time ADD COLUMN uid UUID NOT NULL;
ALTER TABLE feature_measurement_arrival_time ADD COLUMN ig_det_hypo_gid UUID;
ALTER TABLE feature_measurement_arrival_time ADD COLUMN easured_channel_segment_uuid UUID;
ALTER TABLE feature_measurement_arrival_time ADD COLUMN nalysis_channel_segment_uuid UUID;
ALTER TABLE feature_measurement_arrival_time ADD COLUMN ilterid BIGINT;
ALTER TABLE feature_measurement_arrival_time ADD COLUMN ilter_usage VARCHAR(32);
ALTER TABLE feature_measurement_arrival_time ADD COLUMN han_canonical_name VARCHAR(32);
ALTER TABLE feature_measurement_arrival_time ADD COLUMN han_effective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_measurement_arrival_time ADD COLUMN easurement_type VARCHAR(27);
ALTER TABLE feature_measurement_arrival_time ADD COLUMN rrival_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_measurement_arrival_time ADD COLUMN tandard_deviation BINARY_FLOAT;
ALTER TABLE feature_measurement_arrival_time ADD COLUMN nr BINARY_FLOAT;
ALTER TABLE feature_measurement_arrival_time ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_measurement_enumerated ADD COLUMN uid UUID NOT NULL;
ALTER TABLE feature_measurement_enumerated ADD COLUMN ig_det_hypo_gid UUID;
ALTER TABLE feature_measurement_enumerated ADD COLUMN easured_channel_segment_uuid UUID;
ALTER TABLE feature_measurement_enumerated ADD COLUMN nalysis_channel_segment_uuid UUID;
ALTER TABLE feature_measurement_enumerated ADD COLUMN ilterid BIGINT;
ALTER TABLE feature_measurement_enumerated ADD COLUMN ilter_usage VARCHAR(32);
ALTER TABLE feature_measurement_enumerated ADD COLUMN han_canonical_name VARCHAR(32);
ALTER TABLE feature_measurement_enumerated ADD COLUMN han_effective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_measurement_enumerated ADD COLUMN easurement_type VARCHAR(20);
ALTER TABLE feature_measurement_enumerated ADD COLUMN easured_value VARCHAR(13);
ALTER TABLE feature_measurement_enumerated ADD COLUMN onfidence BINARY_FLOAT;
ALTER TABLE feature_measurement_enumerated ADD COLUMN eference_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_measurement_enumerated ADD COLUMN nr BINARY_FLOAT;
ALTER TABLE feature_measurement_enumerated ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_measurement_numeric ADD COLUMN uid UUID NOT NULL;
ALTER TABLE feature_measurement_numeric ADD COLUMN ig_det_hypo_gid UUID;
ALTER TABLE feature_measurement_numeric ADD COLUMN easured_channel_segment_uuid UUID;
ALTER TABLE feature_measurement_numeric ADD COLUMN nalysis_channel_segment_uuid UUID;
ALTER TABLE feature_measurement_numeric ADD COLUMN ilterid BIGINT;
ALTER TABLE feature_measurement_numeric ADD COLUMN ilter_usage VARCHAR(32);
ALTER TABLE feature_measurement_numeric ADD COLUMN han_canonical_name VARCHAR(32);
ALTER TABLE feature_measurement_numeric ADD COLUMN han_effective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_measurement_numeric ADD COLUMN easurement_type VARCHAR(27);
ALTER TABLE feature_measurement_numeric ADD COLUMN easured_value BINARY_FLOAT;
ALTER TABLE feature_measurement_numeric ADD COLUMN nits VARCHAR(32);
ALTER TABLE feature_measurement_numeric ADD COLUMN tandard_deviation BINARY_FLOAT;
ALTER TABLE feature_measurement_numeric ADD COLUMN eference_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_measurement_numeric ADD COLUMN nr BINARY_FLOAT;
ALTER TABLE feature_measurement_numeric ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_prediction_arrival_time ADD COLUMN uid UUID NOT NULL;
ALTER TABLE feature_prediction_arrival_time ADD COLUMN ocation_behavior_uuid UUID;
ALTER TABLE feature_prediction_arrival_time ADD COLUMN han_canonical_name VARCHAR(32);
ALTER TABLE feature_prediction_arrival_time ADD COLUMN han_effective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_prediction_arrival_time ADD COLUMN hase VARCHAR(8);
ALTER TABLE feature_prediction_arrival_time ADD COLUMN rediction_type VARCHAR(27);
ALTER TABLE feature_prediction_arrival_time ADD COLUMN rrival_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_prediction_arrival_time ADD COLUMN ravel_time BINARY_FLOAT;
ALTER TABLE feature_prediction_arrival_time ADD COLUMN tandard_deviation BINARY_FLOAT;
ALTER TABLE feature_prediction_arrival_time ADD COLUMN xtrapolated VARCHAR(1);
ALTER TABLE feature_prediction_arrival_time ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_prediction_component ADD COLUMN uid UUID NOT NULL;
ALTER TABLE feature_prediction_component ADD COLUMN eature_prediction_uuid UUID;
ALTER TABLE feature_prediction_component ADD COLUMN rediction_component_type VARCHAR(35);
ALTER TABLE feature_prediction_component ADD COLUMN alue BINARY_FLOAT;
ALTER TABLE feature_prediction_component ADD COLUMN xtrapolated VARCHAR(1);
ALTER TABLE feature_prediction_component ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_prediction_numeric ADD COLUMN uid UUID NOT NULL;
ALTER TABLE feature_prediction_numeric ADD COLUMN ocation_behavior_uuid UUID;
ALTER TABLE feature_prediction_numeric ADD COLUMN han_canonical_name VARCHAR(32);
ALTER TABLE feature_prediction_numeric ADD COLUMN han_effective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE feature_prediction_numeric ADD COLUMN hase VARCHAR(8);
ALTER TABLE feature_prediction_numeric ADD COLUMN rediction_type VARCHAR(27);
ALTER TABLE feature_prediction_numeric ADD COLUMN redicted_value BINARY_FLOAT;
ALTER TABLE feature_prediction_numeric ADD COLUMN nits VARCHAR(32);
ALTER TABLE feature_prediction_numeric ADD COLUMN tandard_deviation BINARY_FLOAT;
ALTER TABLE feature_prediction_numeric ADD COLUMN xtrapolated VARCHAR(1);
ALTER TABLE feature_prediction_numeric ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE interval ADD COLUMN uid UUID NOT NULL;
ALTER TABLE interval ADD COLUMN nterval_gid UUID;
ALTER TABLE interval ADD COLUMN emark_gid UUID;
ALTER TABLE interval ADD COLUMN tatus VARCHAR(16);
ALTER TABLE interval ADD COLUMN tart_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE interval ADD COLUMN nd_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE interval ADD COLUMN rocessing_start_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE interval ADD COLUMN rocessing_end_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE interval ADD COLUMN ercent_completed BINARY_FLOAT;
ALTER TABLE interval ADD COLUMN ctive_analyst_ids VARCHAR(256);
ALTER TABLE interval ADD COLUMN eserved_analyst_id VARCHAR(32);
ALTER TABLE interval ADD COLUMN ompleted_analyst_id VARCHAR(32);
ALTER TABLE interval ADD COLUMN uthor VARCHAR(32);
ALTER TABLE interval ADD COLUMN tage VARCHAR(32);
ALTER TABLE interval ADD COLUMN tage_mode VARCHAR(32);
ALTER TABLE interval ADD COLUMN ub_stage VARCHAR(64);
ALTER TABLE interval ADD COLUMN ast_executed_step_name VARCHAR(32);
ALTER TABLE interval ADD COLUMN scurrent VARCHAR(1);
ALTER TABLE interval ADD COLUMN oddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE interval ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE location_behavior ADD COLUMN uid UUID NOT NULL;
ALTER TABLE location_behavior ADD COLUMN ocation_solution_uuid UUID;
ALTER TABLE location_behavior ADD COLUMN ig_det_hypo_gid UUID;
ALTER TABLE location_behavior ADD COLUMN eature_measurement_uuid UUID;
ALTER TABLE location_behavior ADD COLUMN eature_prediction_uuid UUID;
ALTER TABLE location_behavior ADD COLUMN alue_type VARCHAR(12);
ALTER TABLE location_behavior ADD COLUMN efining VARCHAR(1);
ALTER TABLE location_behavior ADD COLUMN equested_defining VARCHAR(1);
ALTER TABLE location_behavior ADD COLUMN esidual BINARY_FLOAT;
ALTER TABLE location_behavior ADD COLUMN eight BINARY_FLOAT;
ALTER TABLE location_behavior ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE location_restraint ADD COLUMN uid UUID NOT NULL;
ALTER TABLE location_restraint ADD COLUMN ocation_solution_uuid UUID;
ALTER TABLE location_restraint ADD COLUMN epth_restraint_type VARCHAR(12);
ALTER TABLE location_restraint ADD COLUMN epth_restraint_km BINARY_FLOAT;
ALTER TABLE location_restraint ADD COLUMN epth_restraint_reason VARCHAR(51);
ALTER TABLE location_restraint ADD COLUMN picenter_restraint_type VARCHAR(12);
ALTER TABLE location_restraint ADD COLUMN atitude_restraint_deg BINARY_FLOAT;
ALTER TABLE location_restraint ADD COLUMN ongitude_restraint_deg BINARY_FLOAT;
ALTER TABLE location_restraint ADD COLUMN ime_restraint_type VARCHAR(12);
ALTER TABLE location_restraint ADD COLUMN ime_restraint TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE location_restraint ADD COLUMN estrainer VARCHAR(22);
ALTER TABLE location_restraint ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE location_solution ADD COLUMN uid UUID NOT NULL;
ALTER TABLE location_solution ADD COLUMN vent_hypothesis_uuid UUID;
ALTER TABLE location_solution ADD COLUMN emark_gid UUID;
ALTER TABLE location_solution ADD COLUMN at BINARY_FLOAT;
ALTER TABLE location_solution ADD COLUMN on BINARY_FLOAT;
ALTER TABLE location_solution ADD COLUMN epth BINARY_FLOAT;
ALTER TABLE location_solution ADD COLUMN ime TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE location_solution ADD COLUMN rn NUMERIC(8);
ALTER TABLE location_solution ADD COLUMN rn NUMERIC(8);
ALTER TABLE location_solution ADD COLUMN lgorithm VARCHAR(15);
ALTER TABLE location_solution ADD COLUMN uthor VARCHAR(32);
ALTER TABLE location_solution ADD COLUMN tage VARCHAR(32);
ALTER TABLE location_solution ADD COLUMN scurrent VARCHAR(1);
ALTER TABLE location_solution ADD COLUMN oddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE location_solution ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE location_uncertainty ADD COLUMN uid UUID NOT NULL;
ALTER TABLE location_uncertainty ADD COLUMN ocation_solution_uuid UUID;
ALTER TABLE location_uncertainty ADD COLUMN emark_gid UUID;
ALTER TABLE location_uncertainty ADD COLUMN x BINARY_FLOAT;
ALTER TABLE location_uncertainty ADD COLUMN y BINARY_FLOAT;
ALTER TABLE location_uncertainty ADD COLUMN z BINARY_FLOAT;
ALTER TABLE location_uncertainty ADD COLUMN t BINARY_FLOAT;
ALTER TABLE location_uncertainty ADD COLUMN y BINARY_FLOAT;
ALTER TABLE location_uncertainty ADD COLUMN z BINARY_FLOAT;
ALTER TABLE location_uncertainty ADD COLUMN z BINARY_FLOAT;
ALTER TABLE location_uncertainty ADD COLUMN x BINARY_FLOAT;
ALTER TABLE location_uncertainty ADD COLUMN y BINARY_FLOAT;
ALTER TABLE location_uncertainty ADD COLUMN z BINARY_FLOAT;
ALTER TABLE location_uncertainty ADD COLUMN td_dev_travel_time_residuals BINARY_FLOAT;
ALTER TABLE location_uncertainty ADD COLUMN tage VARCHAR(32);
ALTER TABLE location_uncertainty ADD COLUMN scurrent VARCHAR(1);
ALTER TABLE location_uncertainty ADD COLUMN oddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE location_uncertainty ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE location_uncertainty_ellipse ADD COLUMN uid UUID NOT NULL;
ALTER TABLE location_uncertainty_ellipse ADD COLUMN ocation_uncertainty_uuid UUID;
ALTER TABLE location_uncertainty_ellipse ADD COLUMN caling_factor_type VARCHAR(32);
ALTER TABLE location_uncertainty_ellipse ADD COLUMN _weight BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipse ADD COLUMN onfidence_level BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipse ADD COLUMN priori_variance BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipse ADD COLUMN emi_major_axis_length_km BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipse ADD COLUMN emi_major_axis_trend_deg BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipse ADD COLUMN emi_minor_axis_length_km BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipse ADD COLUMN epth_uncertainty_km BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipse ADD COLUMN ime_uncertainty BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipse ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE location_uncertainty_ellipsoid ADD COLUMN uid UUID NOT NULL;
ALTER TABLE location_uncertainty_ellipsoid ADD COLUMN ocation_uncertainty_uuid UUID;
ALTER TABLE location_uncertainty_ellipsoid ADD COLUMN caling_factor_type VARCHAR(32);
ALTER TABLE location_uncertainty_ellipsoid ADD COLUMN _weight BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipsoid ADD COLUMN onfidence_level BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipsoid ADD COLUMN priori_variance BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipsoid ADD COLUMN emi_major_axis_length_km BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipsoid ADD COLUMN emi_major_axis_trend_deg BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipsoid ADD COLUMN emi_major_axis_plunge_deg BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipsoid ADD COLUMN emi_intermediate_axis_length_km BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipsoid ADD COLUMN emi_intermediate_axis_trend_deg BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipsoid ADD COLUMN emi_intermediate_axis_plunge_deg BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipsoid ADD COLUMN emi_minor_axis_length_km BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipsoid ADD COLUMN emi_minor_axis_trend_km BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipsoid ADD COLUMN emi_minor_axis_plunge_km BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipsoid ADD COLUMN ime_uncertainty BINARY_FLOAT;
ALTER TABLE location_uncertainty_ellipsoid ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE network_magnitude_solution ADD COLUMN uid UUID NOT NULL;
ALTER TABLE network_magnitude_solution ADD COLUMN ocation_solution_uuid UUID;
ALTER TABLE network_magnitude_solution ADD COLUMN vent_hypothesis_uuid UUID;
ALTER TABLE network_magnitude_solution ADD COLUMN emark_gid UUID;
ALTER TABLE network_magnitude_solution ADD COLUMN agtype VARCHAR(6);
ALTER TABLE network_magnitude_solution ADD COLUMN agnitude BINARY_FLOAT;
ALTER TABLE network_magnitude_solution ADD COLUMN ncertainty BINARY_FLOAT;
ALTER TABLE network_magnitude_solution ADD COLUMN tatus VARCHAR(32);
ALTER TABLE network_magnitude_solution ADD COLUMN uthor VARCHAR(32);
ALTER TABLE network_magnitude_solution ADD COLUMN tage VARCHAR(32);
ALTER TABLE network_magnitude_solution ADD COLUMN scurrent VARCHAR(1);
ALTER TABLE network_magnitude_solution ADD COLUMN oddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE network_magnitude_solution ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE processing_mask ADD COLUMN uid UUID NOT NULL;
ALTER TABLE processing_mask ADD COLUMN rocessing_operation VARCHAR(32);
ALTER TABLE processing_mask ADD COLUMN aw_chan_canonical_name VARCHAR(32);
ALTER TABLE processing_mask ADD COLUMN aw_chan_effective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE processing_mask ADD COLUMN tart_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE processing_mask ADD COLUMN nd_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE processing_mask ADD COLUMN ffective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE processing_mask ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE processing_mask_qc_segment_version ADD COLUMN uid UUID NOT NULL;
ALTER TABLE processing_mask_qc_segment_version ADD COLUMN rocessing_mask_uuid UUID NOT NULL;
ALTER TABLE processing_mask_qc_segment_version ADD COLUMN c_segment_version_uuid UUID NOT NULL;
ALTER TABLE processing_mask_qc_segment_version ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE qc_segment_version ADD COLUMN uid UUID NOT NULL;
ALTER TABLE qc_segment_version ADD COLUMN c_segment_gid UUID;
ALTER TABLE qc_segment_version ADD COLUMN han_canonical_name VARCHAR(32);
ALTER TABLE qc_segment_version ADD COLUMN han_effective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE qc_segment_version ADD COLUMN tart_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE qc_segment_version ADD COLUMN nd_time TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE qc_segment_version ADD COLUMN ategory VARCHAR(32);
ALTER TABLE qc_segment_version ADD COLUMN ype VARCHAR(32);
ALTER TABLE qc_segment_version ADD COLUMN ationale VARCHAR(32);
ALTER TABLE qc_segment_version ADD COLUMN ejected VARCHAR(1);
ALTER TABLE qc_segment_version ADD COLUMN uthor VARCHAR(32);
ALTER TABLE qc_segment_version ADD COLUMN tage VARCHAR(32);
ALTER TABLE qc_segment_version ADD COLUMN scurrent VARCHAR(1);
ALTER TABLE qc_segment_version ADD COLUMN ffective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE qc_segment_version ADD COLUMN oddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE qc_segment_version ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE qc_segment_version ADD COLUMN cmaskid BIGINT;
ALTER TABLE remark ADD COLUMN uid UUID NOT NULL;
ALTER TABLE remark ADD COLUMN emark_gid UUID NOT NULL;
ALTER TABLE remark ADD COLUMN emark VARCHAR(256);
ALTER TABLE remark ADD COLUMN uthor VARCHAR(32);
ALTER TABLE remark ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE signal_detection_hypothesis ADD COLUMN uid UUID NOT NULL;
ALTER TABLE signal_detection_hypothesis ADD COLUMN arent_sig_det_hypo_uuid UUID;
ALTER TABLE signal_detection_hypothesis ADD COLUMN ig_det_hypo_gid UUID;
ALTER TABLE signal_detection_hypothesis ADD COLUMN emark_gid UUID;
ALTER TABLE signal_detection_hypothesis ADD COLUMN ta_name VARCHAR(6);
ALTER TABLE signal_detection_hypothesis ADD COLUMN ta_effective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE signal_detection_hypothesis ADD COLUMN onitoring_organization VARCHAR(32);
ALTER TABLE signal_detection_hypothesis ADD COLUMN eleted VARCHAR(1);
ALTER TABLE signal_detection_hypothesis ADD COLUMN uthor VARCHAR(32);
ALTER TABLE signal_detection_hypothesis ADD COLUMN tage VARCHAR(32);
ALTER TABLE signal_detection_hypothesis ADD COLUMN scurrent VARCHAR(1);
ALTER TABLE signal_detection_hypothesis ADD COLUMN oddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE signal_detection_hypothesis ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE stage_metrics ADD COLUMN uid UUID NOT NULL;
ALTER TABLE stage_metrics ADD COLUMN nterval_uuid UUID;
ALTER TABLE stage_metrics ADD COLUMN nterval_gid UUID;
ALTER TABLE stage_metrics ADD COLUMN etric_name VARCHAR(32);
ALTER TABLE stage_metrics ADD COLUMN etric_value VARCHAR(32);
ALTER TABLE stage_metrics ADD COLUMN tage VARCHAR(32);
ALTER TABLE stage_metrics ADD COLUMN scurrent VARCHAR(1);
ALTER TABLE stage_metrics ADD COLUMN oddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE stage_metrics ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_magnitude_solution ADD COLUMN uid UUID NOT NULL;
ALTER TABLE station_magnitude_solution ADD COLUMN eature_measurement_amplitude_uuid UUID;
ALTER TABLE station_magnitude_solution ADD COLUMN etwork_magnitude_solution_uuid UUID;
ALTER TABLE station_magnitude_solution ADD COLUMN emark_gid UUID;
ALTER TABLE station_magnitude_solution ADD COLUMN ta_name VARCHAR(6);
ALTER TABLE station_magnitude_solution ADD COLUMN ta_effective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_magnitude_solution ADD COLUMN hase VARCHAR(8);
ALTER TABLE station_magnitude_solution ADD COLUMN elta BINARY_FLOAT;
ALTER TABLE station_magnitude_solution ADD COLUMN agtype VARCHAR(6);
ALTER TABLE station_magnitude_solution ADD COLUMN agnitude BINARY_FLOAT;
ALTER TABLE station_magnitude_solution ADD COLUMN ncertainty BINARY_FLOAT;
ALTER TABLE station_magnitude_solution ADD COLUMN esidual BINARY_FLOAT;
ALTER TABLE station_magnitude_solution ADD COLUMN eight BINARY_FLOAT;
ALTER TABLE station_magnitude_solution ADD COLUMN efining VARCHAR(1);
ALTER TABLE station_magnitude_solution ADD COLUMN equested_defining VARCHAR(32);
ALTER TABLE station_magnitude_solution ADD COLUMN ttenuation_model VARCHAR(32);
ALTER TABLE station_magnitude_solution ADD COLUMN odel_correction BINARY_FLOAT;
ALTER TABLE station_magnitude_solution ADD COLUMN tation_correction BINARY_FLOAT;
ALTER TABLE station_magnitude_solution ADD COLUMN uthor VARCHAR(32);
ALTER TABLE station_magnitude_solution ADD COLUMN tage VARCHAR(32);
ALTER TABLE station_magnitude_solution ADD COLUMN scurrent VARCHAR(1);
ALTER TABLE station_magnitude_solution ADD COLUMN oddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_magnitude_solution ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE response_table ADD COLUMN nid BIGINT NOT NULL;
ALTER TABLE response_table ADD COLUMN sptype VARCHAR(6) NOT NULL;
ALTER TABLE response_table ADD COLUMN esponse_file TEXT;
ALTER TABLE station_channel ADD COLUMN d UUID NOT NULL;
ALTER TABLE station_channel ADD COLUMN ta_name VARCHAR(6);
ALTER TABLE station_channel ADD COLUMN ta_description VARCHAR(50);
ALTER TABLE station_channel ADD COLUMN ta_type VARCHAR(19);
ALTER TABLE station_channel ADD COLUMN ta_lat BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN ta_lon BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN ta_elev BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN han_grp_name VARCHAR(6);
ALTER TABLE station_channel ADD COLUMN han_grp_description VARCHAR(50);
ALTER TABLE station_channel ADD COLUMN han_grp_type VARCHAR(50);
ALTER TABLE station_channel ADD COLUMN han_grp_lat BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN han_grp_lon BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN han_grp_elev BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN han_grp_north_displacement BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN han_grp_east_displacement BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN han_name VARCHAR(8);
ALTER TABLE station_channel ADD COLUMN han_canonical_name VARCHAR(32);
ALTER TABLE station_channel ADD COLUMN han_description VARCHAR(50);
ALTER TABLE station_channel ADD COLUMN han_data_type VARCHAR(13);
ALTER TABLE station_channel ADD COLUMN han_lat BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN han_lon BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN han_elev BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN han_edepth BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN han_hang BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN han_vang BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN han_band_type VARCHAR(39);
ALTER TABLE station_channel ADD COLUMN han_instrument_type VARCHAR(21);
ALTER TABLE station_channel ADD COLUMN han_orientation_code VARCHAR(1);
ALTER TABLE station_channel ADD COLUMN han_orientation_type VARCHAR(12);
ALTER TABLE station_channel ADD COLUMN han_samprate BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN han_units VARCHAR(22);
ALTER TABLE station_channel ADD COLUMN hanid BIGINT;
ALTER TABLE station_channel ADD COLUMN esponse_cal_factor BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN esponse_cal_period BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN esponse_cal_timeshift BINARY_FLOAT;
ALTER TABLE station_channel ADD COLUMN nid BIGINT;
ALTER TABLE station_channel ADD COLUMN ta_effective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_channel ADD COLUMN ta_effective_until TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_channel ADD COLUMN ta_updated_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_channel ADD COLUMN han_grp_effective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_channel ADD COLUMN han_grp_effective_until TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_channel ADD COLUMN han_grp_updated_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_channel ADD COLUMN han_effective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_channel ADD COLUMN han_effective_until TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_channel ADD COLUMN han_updated_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_channel ADD COLUMN esponse_effective_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_channel ADD COLUMN esponse_effective_until TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_channel ADD COLUMN esponse_updated_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_channel ADD COLUMN scurrent VARCHAR(1) NOT NULL;
ALTER TABLE station_channel ADD COLUMN oddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_channel ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_group_version ADD COLUMN ta_grp_name VARCHAR(8) NOT NULL;
ALTER TABLE station_group_version ADD COLUMN ta_grp_description VARCHAR(120);
ALTER TABLE station_group_version ADD COLUMN ta_grp_effective_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL;
ALTER TABLE station_group_version ADD COLUMN ta_grp_effective_until TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_group_version ADD COLUMN ta_grp_updated_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE station_group_version ADD COLUMN ddate TIMESTAMP(6) WITHOUT TIME ZONE;
