-- Test a single table creation
DROP TABLE IF EXISTS ACTIVE_ID CASCADE;

CREATE TABLE ACTIVE_ID (
    TAGNAME VARCHAR(8),
    TAGID BIGINT,
    CLIENT_INFO VARCHAR(64),
    AUTHOR VARCHAR(64),
    MODDATE TIMESTAMP,
    LDDATE TIMESTAMP
);