-- USNDC Schema Deployment Batch 7
-- Tables in this batch: 20

CREATE TABLE OUTAGE_STATION_RECEIVE (
    OUTAGE_ID BIGINT
    STA VARCHAR(6)
    START_DATE TIMESTAMP
    END_DATE TIMESTAMP
    ENDTIME DOUBLE PRECISION
    AUTHOR VARCHAR(64)
    MODDATE TIMESTAMP
    LDDATE TIMESTAMP
);

CREATE TABLE POLYGON (
    POLYID BIGINT
    REGION_NAME VARCHAR(30)
    PERIMETERTYPE VARCHAR(8)
    INSIDEFLAG VARCHAR(1)
    OUTSIDEFLAG VARCHAR(1)
    EDGEFLAG VARCHAR(1)
    AUTH VARCHAR(15)
    COMMENTS VARCHAR(4000)
    LDDATE TIMESTAMP
);

CREATE TABLE POLYPOINT (
    POLYID BIGINT
    SEQUENCE BIGINT
    LAT DOUBLE PRECISION
    LON DOUBLE PRECISION
    LDDATE TIMESTAMP
);

CREATE TABLE PROCESSING_RECIPE (
    PROCID BIGINT
    PROCMETHOD VARCHAR(20)
    IDNAME VARCHAR(15)
    IDVALUE BIGINT
    PROCORDER INTEGER
    AUTH VARCHAR(15)
    LDDATE TIMESTAMP
);

CREATE TABLE PROCESS_TRACKING (
    TRACKINGID BIGINT
    PROCESS VARCHAR(256)
    MACHINE VARCHAR(128)
    SYS_AREA VARCHAR(128)
    SYS_SITE VARCHAR(128)
    PROC_START_DATE TIMESTAMP
    PROC_END_DATE TIMESTAMP
    STATE VARCHAR(16)
    AUTHOR VARCHAR(64)
    MODDATE TIMESTAMP
    LDDATE TIMESTAMP
);

CREATE TABLE QCMASKINFO (
    QCMASKID BIGINT
    STA VARCHAR(6)
    CHAN VARCHAR(8)
    TIME DOUBLE PRECISION
    ENDTIME DOUBLE PRECISION
    SAMPRATE REAL
    NSEG INTEGER
    QCDEFID BIGINT
    AUTH VARCHAR(15)
    LDDATE TIMESTAMP
);

CREATE TABLE QCMASKSEG (
    QCMASKID BIGINT
    STARTSAMPLE INTEGER
    ENDSAMPLE INTEGER
    MASKTYPE INTEGER
    AUTH VARCHAR(15)
    LDDATE TIMESTAMP
);

CREATE TABLE QSHELL_INTERVAL (
    QSHELL_INTVLID BIGINT
    INTVLID BIGINT
    CLASS VARCHAR(16)
    NAME VARCHAR(20)
    PROC_START_DATE TIMESTAMP
    PROC_END_DATE TIMESTAMP
    STATE VARCHAR(16)
    AUTHOR VARCHAR(64)
    MODDATE TIMESTAMP
    LDDATE TIMESTAMP
);

CREATE TABLE RDA_PARAM (
    POLYID BIGINT
    RDA_VERID BIGINT
    GAMMA DOUBLE PRECISION
    LAMBDA DOUBLE PRECISION
    CLASS_DECISION_THRESH DOUBLE PRECISION
    AUTH VARCHAR(15)
    COMMENTS VARCHAR(4000)
    LDDATE TIMESTAMP
);

CREATE TABLE REG_RATIO_DISCRIM (
    POLYID BIGINT
    COV_VERID BIGINT
    NUMERATOR_PHASE VARCHAR(8)
    DENOMINATOR_PHASE VARCHAR(8)
    NUM_LOW_FREQ DOUBLE PRECISION
    NUM_HI_FREQ DOUBLE PRECISION
    DEN_LOW_FREQ DOUBLE PRECISION
    DEN_HI_FREQ DOUBLE PRECISION
    MEAN_EX_VAL DOUBLE PRECISION
    NUM_STATION_VAR DOUBLE PRECISION
    DEN_STATION_VAR DOUBLE PRECISION
    NUM_EVENT_VAR DOUBLE PRECISION
    DEN_EVENT_VAR DOUBLE PRECISION
    LDDATE TIMESTAMP
);

CREATE TABLE REMARK (
    COMMID BIGINT
    LINENO INTEGER
    REMARK VARCHAR(160)
    LDDATE TIMESTAMP
    CONSTRAINT pk_remark PRIMARY KEY (COMMID)
);

CREATE TABLE REMOVED_BEAM_DFILE (
    DFILE VARCHAR(32)
    LDDATE TIMESTAMP
);

CREATE TABLE REQUEST (
    REQID BIGINT
    STA VARCHAR(6)
    CHAN VARCHAR(8)
    ARRAY VARCHAR(8)
    ORID BIGINT
    EVID BIGINT
    TIME DOUBLE PRECISION
    ENDTIME DOUBLE PRECISION
    CLASS VARCHAR(16)
    REQ_STATE VARCHAR(16)
    STATECOUNT INTEGER
    COMPLETE INTEGER
    REQUESTOR VARCHAR(15)
    MODTIME DOUBLE PRECISION
    MODAUTHOR VARCHAR(15)
    LDDATE TIMESTAMP
);

CREATE TABLE SADO_EMAIL_HISTORY (
    SADO_EMAIL_ID BIGINT
    REPORT_ID BIGINT
    SUBJECT VARCHAR(1000)
    RECIPIENTS VARCHAR(4000)
    AUTHOR VARCHAR(64)
    MODDATE TIMESTAMP
    LDDATE TIMESTAMP
);

CREATE TABLE SADO_PDF_REPORTS (
    SADO_PDF_REPORT_ID BIGINT
    REPORT_ID BIGINT
    AUTHOR VARCHAR(64)
    MODDATE TIMESTAMP
    LDDATE TIMESTAMP
);

CREATE TABLE SADO_REPORT (
    REPORT_ID BIGINT
    EVID BIGINT
    ORID BIGINT
    GRN INTEGER
    EVENT_TIME DOUBLE PRECISION
    TITLE VARCHAR(64)
    ANALYST VARCHAR(32)
    ACCOUNT VARCHAR(15)
    CLASSIFICATION VARCHAR(256)
    TTGE VARCHAR(1)
    SADO_RELEASED VARCHAR(1)
    ALERT_MANAGER_CALLED VARCHAR(1)
    EXERCISE VARCHAR(1)
    EMAIL_TYPE VARCHAR(32)
    ALERT_MANAGER VARCHAR(64)
    YIELD_CALCULATOR_REGION_SELECT VARCHAR(64)
    FINAL_DETERMINATION VARCHAR(32)
    MAG_MAGTYPE VARCHAR(32)
    OVERBURDEN_SET VARCHAR(1)
    OVERBURDEN REAL
    COMMENTS VARCHAR(4000)
    ECM_DETERMINATION VARCHAR(32)
    AUTHOR VARCHAR(64)
    MODDATE TIMESTAMP
    LDDATE TIMESTAMP
);

CREATE TABLE SADO_REPORT_LANDMARKS (
    REPORT_LANDMARKS_ID BIGINT
    REPORT_ID BIGINT
    LOCATION_ID BIGINT
    TESTSITE VARCHAR(1)
    NAME VARCHAR(64)
    LAT REAL
    LON REAL
    DISTANCE REAL
    AUTHOR VARCHAR(64)
    MODDATE TIMESTAMP
    LDDATE TIMESTAMP
);

CREATE TABLE SADO_SCREENSHOTS (
    SADO_SCREENSHOT_ID BIGINT
    REPORT_ID BIGINT
    TYPE VARCHAR(10)
    AUTHOR VARCHAR(64)
    MODDATE TIMESTAMP
    LDDATE TIMESTAMP
);

CREATE TABLE SADO_STATE (
    SADO_STATE_ID BIGINT
    REPORT_ID BIGINT
    SADO_STATE_CATEGORY_ID BIGINT
    AUTHOR VARCHAR(64)
    MODDATE TIMESTAMP
    LDDATE TIMESTAMP
);

CREATE TABLE SADO_STATE_CATEGORIES (
    SADO_STATE_CATEGORY_ID BIGINT
    TITLE VARCHAR(64)
    AUTHOR VARCHAR(64)
    MODDATE TIMESTAMP
    LDDATE TIMESTAMP
);

