-- USNDC Schema Deployment Batch 9
-- Tables in this batch: 5

CREATE TABLE WFAUDIT (
    WFAUDITID BIGINT
    STA VARCHAR(6)
    CHAN VARCHAR(8)
    OLD_TIME DOUBLE PRECISION
    NEW_TIME DOUBLE PRECISION
    OLD_ENDTIME DOUBLE PRECISION
    NEW_ENDTIME DOUBLE PRECISION
    MODDATE TIMESTAMP
);

CREATE TABLE WFCONV (
    STA VARCHAR(6)
    CHAN VARCHAR(8)
    CHANID BIGINT
    INAUTH VARCHAR(1)
    INCOMP VARCHAR(2)
    INTYPE VARCHAR(2)
    INSAMP INTEGER
    OUTAUTH VARCHAR(1)
    OUTCOMP VARCHAR(2)
    OUTTYPE VARCHAR(2)
    OUTSAMP INTEGER
    STRIP VARCHAR(1)
    COMMID BIGINT
    LDDATE TIMESTAMP
);

CREATE TABLE WFDISC (
    STA VARCHAR(6)
    CHAN VARCHAR(8)
    TIME DOUBLE PRECISION
    WFID BIGINT
    CHANID BIGINT
    JDATE INTEGER
    ENDTIME DOUBLE PRECISION
    NSAMP INTEGER
    SAMPRATE REAL
    CALIB REAL
    CALPER REAL
    INSTYPE VARCHAR(6)
    SEGTYPE VARCHAR(1)
    DATATYPE VARCHAR(2)
    CLIP VARCHAR(1)
    DIR VARCHAR(64)
    DFILE VARCHAR(32)
    FOFF BIGINT
    COMMID BIGINT
    LDDATE TIMESTAMP
    CONSTRAINT pk_wfdisc PRIMARY KEY (WFID)
);

CREATE TABLE WFTAG (
    TAGNAME VARCHAR(8)
    TAGID BIGINT
    WFID BIGINT
    LDDATE TIMESTAMP
    CONSTRAINT pk_wftag PRIMARY KEY (TAGID, WFID)
);

CREATE TABLE XTAG (
    THISID BIGINT
    THATID BIGINT
    THISNAME VARCHAR(8)
    THATNAME VARCHAR(8)
    THISDB VARCHAR(32)
    THATDB VARCHAR(32)
    LDDATE TIMESTAMP
);

