-- USNDC Foreign Key Constraints
-- Extracted 210 foreign key constraints

ALTER TABLE AFFILIATION ADD CONSTRAINT fk_affiliation_net FOREIGN KEY (NET) REFERENCES DEFINING_RULES (NET);

ALTER TABLE AFFILIATION ADD CONSTRAINT fk_affiliation_sta FOREIGN KEY (STA) REFERENCES ALPHASITE (STA);

ALTER TABLE ALGORITHM ADD CONSTRAINT fk_algorithm_algorithm_id FOREIGN KEY (ALGORITHM_ID) REFERENCES HISTORIC_INFO_SHELL (ALGORITHM_ID);

ALTER TABLE ALPHASITE ADD CONSTRAINT fk_alphasite_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE AMP3C ADD CONSTRAINT fk_amp3c_arid FOREIGN KEY (ARID) REFERENCES AMPLITUDE (ARID);

ALTER TABLE AMPLITUDE ADD CONSTRAINT fk_amplitude_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE AMPLITUDE ADD CONSTRAINT fk_amplitude_chan FOREIGN KEY (CHAN) REFERENCES ARRIVAL (CHAN);

ALTER TABLE APMA ADD CONSTRAINT fk_apma_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE ARRIVAL ADD CONSTRAINT fk_arrival_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE ARRIVAL ADD CONSTRAINT fk_arrival_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE ARRIVAL ADD CONSTRAINT fk_arrival_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE ARRIVAL_DYN_PARS_DBL ADD CONSTRAINT fk_arrival_dyn_pars_dbl_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE ARRIVAL_DYN_PARS_INT ADD CONSTRAINT fk_arrival_dyn_pars_int_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE ARRIVAL_DYN_PARS_STR ADD CONSTRAINT fk_arrival_dyn_pars_str_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE ARRIVAL_TAG ADD CONSTRAINT fk_arrival_tag_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE AR_INFO ADD CONSTRAINT fk_ar_info_orid FOREIGN KEY (ORID) REFERENCES ASSOC (ORID);

ALTER TABLE AR_INFO ADD CONSTRAINT fk_ar_info_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE ASSOC ADD CONSTRAINT fk_assoc_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE ASSOC ADD CONSTRAINT fk_assoc_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE ASSOC ADD CONSTRAINT fk_assoc_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE ASSOC_GA ADD CONSTRAINT fk_assoc_ga_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE ASSOC_GA ADD CONSTRAINT fk_assoc_ga_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE ASSOC_GA ADD CONSTRAINT fk_assoc_ga_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE ASSOC_GA_DEL ADD CONSTRAINT fk_assoc_ga_del_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE ASSOC_GA_DEL ADD CONSTRAINT fk_assoc_ga_del_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE ASSOC_GA_DEL ADD CONSTRAINT fk_assoc_ga_del_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE BEAM ADD CONSTRAINT fk_beam_wfid FOREIGN KEY (WFID) REFERENCES WFDISC (WFID);

ALTER TABLE BULLETIN_RELEASE ADD CONSTRAINT fk_bulletin_release_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE BULLETIN_RELEASE ADD CONSTRAINT fk_bulletin_release_evid FOREIGN KEY (EVID) REFERENCES ECM_EVENT_RESULTS (EVID);

ALTER TABLE CHAN_GROUPS ADD CONSTRAINT fk_chan_groups_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE CHAN_GROUPS ADD CONSTRAINT fk_chan_groups_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE CLASSIFICATION ADD CONSTRAINT fk_classification_classification_id FOREIGN KEY (CLASSIFICATION_ID) REFERENCES CLASSIFICATION_LOOKUP (CLASSIFICATION_ID);

ALTER TABLE CLASSIFICATION ADD CONSTRAINT fk_classification_class_level_id FOREIGN KEY (CLASS_LEVEL_ID) REFERENCES CLASSIFICATION_LEVEL (CLASS_LEVEL_ID);

ALTER TABLE CLASSIFICATION ADD CONSTRAINT fk_classification_class_dissem_id FOREIGN KEY (CLASS_DISSEM_ID) REFERENCES CLASS_DISSEM_ID (CLASS_DISSEM_ID);

ALTER TABLE CLASSIFICATION ADD CONSTRAINT fk_classification_class_derived_id FOREIGN KEY (CLASS_DERIVED_ID) REFERENCES CLASS_DERIVED_ID (CLASS_DERIVED_ID);

ALTER TABLE CLASSIFICATION ADD CONSTRAINT fk_classification_class_declass_id FOREIGN KEY (CLASS_DECLASS_ID) REFERENCES CLASS_DECLASS_ID (CLASS_DECLASS_ID);

ALTER TABLE CLASSIFICATION ADD CONSTRAINT fk_classification_class_refer_id FOREIGN KEY (CLASS_REFER_ID) REFERENCES CLASSIFICATION_REFER_TO (CLASS_REFER_ID);

ALTER TABLE CLASSIFICATION ADD CONSTRAINT fk_classification_class_opr_id FOREIGN KEY (CLASS_OPR_ID) REFERENCES CLASSIFICATION_OPR (CLASS_OPR_ID);

ALTER TABLE CLASSIFICATION_LEVEL ADD CONSTRAINT fk_classification_level_class_level_id FOREIGN KEY (CLASS_LEVEL_ID) REFERENCES CLASSIFICATION (CLASS_LEVEL_ID);

ALTER TABLE CLASSIFICATION_LOOKUP ADD CONSTRAINT fk_classification_lookup_classification_id FOREIGN KEY (CLASSIFICATION_ID) REFERENCES CLASSIFICATION (CLASSIFICATION_ID);

ALTER TABLE CLASSIFICATION_OPR ADD CONSTRAINT fk_classification_opr_class_opr_id FOREIGN KEY (CLASS_OPR_ID) REFERENCES CLASSIFICATION (CLASS_OPR_ID);

ALTER TABLE CLASSIFICATION_REFER_TO ADD CONSTRAINT fk_classification_refer_to_class_refer_id FOREIGN KEY (CLASS_REFER_ID) REFERENCES CLASSIFICATION (CLASS_REFER_ID);

ALTER TABLE CLASS_DECLASS_ID ADD CONSTRAINT fk_class_declass_id_class_declass_id FOREIGN KEY (CLASS_DECLASS_ID) REFERENCES CLASSIFICATION (CLASS_DECLASS_ID);

ALTER TABLE CLASS_DERIVED_ID ADD CONSTRAINT fk_class_derived_id_class_derived_id FOREIGN KEY (CLASS_DERIVED_ID) REFERENCES CLASSIFICATION (CLASS_DERIVED_ID);

ALTER TABLE CLASS_DISSEM_ID ADD CONSTRAINT fk_class_dissem_id_class_dissem_id FOREIGN KEY (CLASS_DISSEM_ID) REFERENCES CLASSIFICATION (CLASS_DISSEM_ID);

ALTER TABLE CLUSTER_MAGREF ADD CONSTRAINT fk_cluster_magref_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE CLUSTER_MEC ADD CONSTRAINT fk_cluster_mec_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE CLUSTER_ORID ADD CONSTRAINT fk_cluster_orid_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE CLUSTER_STATION ADD CONSTRAINT fk_cluster_station_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE CLUSTER_THRESHOLD ADD CONSTRAINT fk_cluster_threshold_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE CODAMAG_INPUT ADD CONSTRAINT fk_codamag_input_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE CODAMAG_INPUT ADD CONSTRAINT fk_codamag_input_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE CODAMAG_INPUT ADD CONSTRAINT fk_codamag_input_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE CODAMAG_INPUT ADD CONSTRAINT fk_codamag_input_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE CODAMAG_OUTPUT ADD CONSTRAINT fk_codamag_output_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE CODAMAG_OUTPUT ADD CONSTRAINT fk_codamag_output_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE CODAMAG_OUTPUT ADD CONSTRAINT fk_codamag_output_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE CODAMAG_OUTPUT ADD CONSTRAINT fk_codamag_output_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE CONTINUOUS_DATA_STATUS ADD CONSTRAINT fk_continuous_data_status_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE CONTINUOUS_DATA_STATUS ADD CONSTRAINT fk_continuous_data_status_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE DA_REFSTA_LATENCY ADD CONSTRAINT fk_da_refsta_latency_latency_id FOREIGN KEY (LATENCY_ID) REFERENCES DA_SITECHAN_LATENCY (LATENCY_ID);

ALTER TABLE DA_REFSTA_LATENCY ADD CONSTRAINT fk_da_refsta_latency_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE DA_REFSTA_SUMMARY ADD CONSTRAINT fk_da_refsta_summary_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE DA_SITECHAN_LATENCY ADD CONSTRAINT fk_da_sitechan_latency_latency_id FOREIGN KEY (LATENCY_ID) REFERENCES DA_REFSTA_LATENCY (LATENCY_ID);

ALTER TABLE DA_SITECHAN_LATENCY ADD CONSTRAINT fk_da_sitechan_latency_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE DA_SITECHAN_LATENCY ADD CONSTRAINT fk_da_sitechan_latency_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE DEFINING_OBSTYPES ADD CONSTRAINT fk_defining_obstypes_obstype_id FOREIGN KEY (OBSTYPE_ID) REFERENCES DEFINING_RULES (OBSTYPE_ID);

ALTER TABLE DEFINING_RULES ADD CONSTRAINT fk_defining_rules_net FOREIGN KEY (NET) REFERENCES AFFILIATION (NET);

ALTER TABLE DEFINING_RULES ADD CONSTRAINT fk_defining_rules_obstype_id FOREIGN KEY (OBSTYPE_ID) REFERENCES DEFINING_OBSTYPES (OBSTYPE_ID);

ALTER TABLE DEFINING_RULES ADD CONSTRAINT fk_defining_rules_value_id FOREIGN KEY (VALUE_ID) REFERENCES DEFINING_VALUES (VALUE_ID);

ALTER TABLE DEFINING_VALUES ADD CONSTRAINT fk_defining_values_value_id FOREIGN KEY (VALUE_ID) REFERENCES DEFINING_RULES (VALUE_ID);

ALTER TABLE DETECTION ADD CONSTRAINT fk_detection_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE DETECTION ADD CONSTRAINT fk_detection_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE DETECTION ADD CONSTRAINT fk_detection_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE DETECTION_THRESHOLD ADD CONSTRAINT fk_detection_threshold_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE DETECTION_THRESHOLD ADD CONSTRAINT fk_detection_threshold_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE DISCRIMUSE ADD CONSTRAINT fk_discrimuse_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE DISCRIMUSE ADD CONSTRAINT fk_discrimuse_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE DISCRIMVOTE ADD CONSTRAINT fk_discrimvote_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE DISCRIMVOTE ADD CONSTRAINT fk_discrimvote_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE DISCRIM_PARAM ADD CONSTRAINT fk_discrim_param_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE DISCRIM_PARAM ADD CONSTRAINT fk_discrim_param_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE DOPPLER_DETECTION ADD CONSTRAINT fk_doppler_detection_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE DOPPLER_DETECTION ADD CONSTRAINT fk_doppler_detection_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE ECM_CHAN_AMPLITUDE ADD CONSTRAINT fk_ecm_chan_amplitude_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE ECM_CHAN_AMPLITUDE ADD CONSTRAINT fk_ecm_chan_amplitude_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE ECM_CHAN_AMPLITUDE ADD CONSTRAINT fk_ecm_chan_amplitude_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE ECM_DISCRIMINANTS ADD CONSTRAINT fk_ecm_discriminants_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE ECM_EVENT_RESULTS ADD CONSTRAINT fk_ecm_event_results_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE ECM_EVENT_RESULTS ADD CONSTRAINT fk_ecm_event_results_evid FOREIGN KEY (EVID) REFERENCES BULLETIN_RELEASE (EVID);

ALTER TABLE ECM_REF_CHAN_AMPLITUDE ADD CONSTRAINT fk_ecm_ref_chan_amplitude_evid FOREIGN KEY (EVID) REFERENCES BULLETIN_RELEASE (EVID);

ALTER TABLE ECM_REF_CHAN_AMPLITUDE ADD CONSTRAINT fk_ecm_ref_chan_amplitude_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE ECM_REF_CHAN_AMPLITUDE ADD CONSTRAINT fk_ecm_ref_chan_amplitude_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE ECM_REF_DISCRIM ADD CONSTRAINT fk_ecm_ref_discrim_evid FOREIGN KEY (EVID) REFERENCES BULLETIN_RELEASE (EVID);

ALTER TABLE ECM_REF_EVENT ADD CONSTRAINT fk_ecm_ref_event_evid FOREIGN KEY (EVID) REFERENCES BULLETIN_RELEASE (EVID);

ALTER TABLE ECM_SOURCES ADD CONSTRAINT fk_ecm_sources_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE ECM_STA_PREF_VERSION ADD CONSTRAINT fk_ecm_sta_pref_version_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE ENVELOPE_CONTRIBUTION ADD CONSTRAINT fk_envelope_contribution_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE ENVELOPE_CONTRIBUTION ADD CONSTRAINT fk_envelope_contribution_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE ENVELOPE_CONTRIBUTION ADD CONSTRAINT fk_envelope_contribution_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE ENVELOPE_CONTRIBUTION ADD CONSTRAINT fk_envelope_contribution_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE EVENT ADD CONSTRAINT fk_event_evid FOREIGN KEY (EVID) REFERENCES BULLETIN_RELEASE (EVID);

ALTER TABLE EVENT_CONTROL ADD CONSTRAINT fk_event_control_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE EVENT_CONTROL ADD CONSTRAINT fk_event_control_evid FOREIGN KEY (EVID) REFERENCES BULLETIN_RELEASE (EVID);

ALTER TABLE EVENT_CORRELATION ADD CONSTRAINT fk_event_correlation_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE EVENT_QUALITY ADD CONSTRAINT fk_event_quality_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE FEEDBACK ADD CONSTRAINT fk_feedback_feedback_id FOREIGN KEY (FEEDBACK_ID) REFERENCES FEEDBACK_CATAFFILIATION (FEEDBACK_ID);

ALTER TABLE FEEDBACK ADD CONSTRAINT fk_feedback_evid FOREIGN KEY (EVID) REFERENCES BULLETIN_RELEASE (EVID);

ALTER TABLE FEEDBACK ADD CONSTRAINT fk_feedback_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE FEEDBACK_CATAFFILIATION ADD CONSTRAINT fk_feedback_cataffiliation_feedback_id FOREIGN KEY (FEEDBACK_ID) REFERENCES FEEDBACK (FEEDBACK_ID);

ALTER TABLE FEEDBACK_CATAFFILIATION ADD CONSTRAINT fk_feedback_cataffiliation_fbcategory_id FOREIGN KEY (FBCATEGORY_ID) REFERENCES FEEDBACK_CATEGORIES (FBCATEGORY_ID);

ALTER TABLE FEEDBACK_CATEGORIES ADD CONSTRAINT fk_feedback_categories_fbcategory_id FOREIGN KEY (FBCATEGORY_ID) REFERENCES FEEDBACK_CATAFFILIATION (FBCATEGORY_ID);

ALTER TABLE FEEDBACK_SCREENSHOTS ADD CONSTRAINT fk_feedback_screenshots_feedback_id FOREIGN KEY (FEEDBACK_ID) REFERENCES FEEDBACK (FEEDBACK_ID);

ALTER TABLE FEEDBACK_STATE ADD CONSTRAINT fk_feedback_state_feedback_id FOREIGN KEY (FEEDBACK_ID) REFERENCES FEEDBACK (FEEDBACK_ID);

ALTER TABLE FEEDBACK_STATE ADD CONSTRAINT fk_feedback_state_fbstatecategory_id FOREIGN KEY (FBSTATECATEGORY_ID) REFERENCES FEEDBACK_STATE_CATEGORIES (FBSTATECATEGORY_ID);

ALTER TABLE FEEDBACK_STATE_CATEGORIES ADD CONSTRAINT fk_feedback_state_categories_fbstatecategory_id FOREIGN KEY (FBSTATECATEGORY_ID) REFERENCES FEEDBACK_STATE (FBSTATECATEGORY_ID);

ALTER TABLE FK_PROCESSING ADD CONSTRAINT fk_fk_processing_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE HISTORIC_INFO_CYLINDER ADD CONSTRAINT fk_historic_info_cylinder_historic_info_cylinder_id FOREIGN KEY (HISTORIC_INFO_CYLINDER_ID) REFERENCES HISTORIC_INFO_STA_PHASE (HISTORIC_INFO_CYLINDER_ID);

ALTER TABLE HISTORIC_INFO_SHELL ADD CONSTRAINT fk_historic_info_shell_algorithm_id FOREIGN KEY (ALGORITHM_ID) REFERENCES ALGORITHM (ALGORITHM_ID);

ALTER TABLE HISTORIC_INFO_STA_PHASE ADD CONSTRAINT fk_historic_info_sta_phase_historic_info_cylinder_id FOREIGN KEY (HISTORIC_INFO_CYLINDER_ID) REFERENCES HISTORIC_INFO_CYLINDER (HISTORIC_INFO_CYLINDER_ID);

ALTER TABLE HISTORIC_INFO_STA_PHASE ADD CONSTRAINT fk_historic_info_sta_phase_algorithm_id FOREIGN KEY (ALGORITHM_ID) REFERENCES ALGORITHM (ALGORITHM_ID);

ALTER TABLE HYDRO_ARRIVAL ADD CONSTRAINT fk_hydro_arrival_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE HYDRO_ARRIVAL ADD CONSTRAINT fk_hydro_arrival_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE HYDRO_ARR_GROUP ADD CONSTRAINT fk_hydro_arr_group_hydro_id FOREIGN KEY (HYDRO_ID) REFERENCES HYDRO_ASSOC (HYDRO_ID);

ALTER TABLE HYDRO_ARR_GROUP ADD CONSTRAINT fk_hydro_arr_group_net FOREIGN KEY (NET) REFERENCES AFFILIATION (NET);

ALTER TABLE HYDRO_ASSOC ADD CONSTRAINT fk_hydro_assoc_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE HYDRO_ASSOC ADD CONSTRAINT fk_hydro_assoc_hydro_id FOREIGN KEY (HYDRO_ID) REFERENCES HYDRO_ARR_GROUP (HYDRO_ID);

ALTER TABLE HYDRO_ORIGIN ADD CONSTRAINT fk_hydro_origin_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE MDAC_FD ADD CONSTRAINT fk_mdac_fd_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE MDAC_FD ADD CONSTRAINT fk_mdac_fd_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE MDAC_FI ADD CONSTRAINT fk_mdac_fi_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE MDAC_FI ADD CONSTRAINT fk_mdac_fi_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE MSVMAX_DESCRIPT ADD CONSTRAINT fk_msvmax_descript_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE MSVMAX_DESCRIPT ADD CONSTRAINT fk_msvmax_descript_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE MSVMAX_DESCRIPT ADD CONSTRAINT fk_msvmax_descript_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE NETMAG ADD CONSTRAINT fk_netmag_net FOREIGN KEY (NET) REFERENCES AFFILIATION (NET);

ALTER TABLE NETMAG ADD CONSTRAINT fk_netmag_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE NETMAG ADD CONSTRAINT fk_netmag_evid FOREIGN KEY (EVID) REFERENCES BULLETIN_RELEASE (EVID);

ALTER TABLE NETWORK ADD CONSTRAINT fk_network_net FOREIGN KEY (NET) REFERENCES AFFILIATION (NET);

ALTER TABLE NETYIELD ADD CONSTRAINT fk_netyield_net FOREIGN KEY (NET) REFERENCES AFFILIATION (NET);

ALTER TABLE NETYIELD ADD CONSTRAINT fk_netyield_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE NETYIELD ADD CONSTRAINT fk_netyield_evid FOREIGN KEY (EVID) REFERENCES BULLETIN_RELEASE (EVID);

ALTER TABLE OMITTED_CHANNELS ADD CONSTRAINT fk_omitted_channels_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE OMITTED_CHANNELS ADD CONSTRAINT fk_omitted_channels_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE ORIGERR ADD CONSTRAINT fk_origerr_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE ORIGERR_GA ADD CONSTRAINT fk_origerr_ga_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE ORIGERR_GA_DEL ADD CONSTRAINT fk_origerr_ga_del_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE ORIGIN ADD CONSTRAINT fk_origin_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE ORIGIN ADD CONSTRAINT fk_origin_evid FOREIGN KEY (EVID) REFERENCES BULLETIN_RELEASE (EVID);

ALTER TABLE ORIGIN_GA ADD CONSTRAINT fk_origin_ga_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE ORIGIN_GA ADD CONSTRAINT fk_origin_ga_evid FOREIGN KEY (EVID) REFERENCES BULLETIN_RELEASE (EVID);

ALTER TABLE ORIGIN_GA_DEL ADD CONSTRAINT fk_origin_ga_del_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE ORIGIN_GA_DEL ADD CONSTRAINT fk_origin_ga_del_evid FOREIGN KEY (EVID) REFERENCES BULLETIN_RELEASE (EVID);

ALTER TABLE ORIGIN_MEA_TRACE ADD CONSTRAINT fk_origin_mea_trace_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE ORIGIN_SDO ADD CONSTRAINT fk_origin_sdo_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE ORIGIN_TAG ADD CONSTRAINT fk_origin_tag_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE OUTAGE_STATION_DATA ADD CONSTRAINT fk_outage_station_data_outage_id FOREIGN KEY (OUTAGE_ID) REFERENCES OUTAGE_STATION_RECEIVE (OUTAGE_ID);

ALTER TABLE OUTAGE_STATION_DATA ADD CONSTRAINT fk_outage_station_data_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE OUTAGE_STATION_RECEIVE ADD CONSTRAINT fk_outage_station_receive_outage_id FOREIGN KEY (OUTAGE_ID) REFERENCES OUTAGE_STATION_DATA (OUTAGE_ID);

ALTER TABLE OUTAGE_STATION_RECEIVE ADD CONSTRAINT fk_outage_station_receive_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE QCMASKINFO ADD CONSTRAINT fk_qcmaskinfo_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE QCMASKINFO ADD CONSTRAINT fk_qcmaskinfo_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE REQUEST ADD CONSTRAINT fk_request_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE REQUEST ADD CONSTRAINT fk_request_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE REQUEST ADD CONSTRAINT fk_request_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE REQUEST ADD CONSTRAINT fk_request_evid FOREIGN KEY (EVID) REFERENCES BULLETIN_RELEASE (EVID);

ALTER TABLE SADO_EMAIL_HISTORY ADD CONSTRAINT fk_sado_email_history_report_id FOREIGN KEY (REPORT_ID) REFERENCES SADO_PDF_REPORTS (REPORT_ID);

ALTER TABLE SADO_PDF_REPORTS ADD CONSTRAINT fk_sado_pdf_reports_report_id FOREIGN KEY (REPORT_ID) REFERENCES SADO_EMAIL_HISTORY (REPORT_ID);

ALTER TABLE SADO_REPORT ADD CONSTRAINT fk_sado_report_report_id FOREIGN KEY (REPORT_ID) REFERENCES SADO_EMAIL_HISTORY (REPORT_ID);

ALTER TABLE SADO_REPORT ADD CONSTRAINT fk_sado_report_evid FOREIGN KEY (EVID) REFERENCES BULLETIN_RELEASE (EVID);

ALTER TABLE SADO_REPORT ADD CONSTRAINT fk_sado_report_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE SADO_REPORT_LANDMARKS ADD CONSTRAINT fk_sado_report_landmarks_report_id FOREIGN KEY (REPORT_ID) REFERENCES SADO_EMAIL_HISTORY (REPORT_ID);

ALTER TABLE SADO_SCREENSHOTS ADD CONSTRAINT fk_sado_screenshots_report_id FOREIGN KEY (REPORT_ID) REFERENCES SADO_EMAIL_HISTORY (REPORT_ID);

ALTER TABLE SADO_STATE ADD CONSTRAINT fk_sado_state_report_id FOREIGN KEY (REPORT_ID) REFERENCES SADO_EMAIL_HISTORY (REPORT_ID);

ALTER TABLE SADO_STATE ADD CONSTRAINT fk_sado_state_sado_state_category_id FOREIGN KEY (SADO_STATE_CATEGORY_ID) REFERENCES SADO_STATE_CATEGORIES (SADO_STATE_CATEGORY_ID);

ALTER TABLE SADO_STATE_CATEGORIES ADD CONSTRAINT fk_sado_state_categories_sado_state_category_id FOREIGN KEY (SADO_STATE_CATEGORY_ID) REFERENCES SADO_STATE (SADO_STATE_CATEGORY_ID);

ALTER TABLE SENSOR ADD CONSTRAINT fk_sensor_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE SENSOR ADD CONSTRAINT fk_sensor_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE SITE ADD CONSTRAINT fk_site_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE SITEAUX ADD CONSTRAINT fk_siteaux_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE SITEAUX ADD CONSTRAINT fk_siteaux_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE SITECHAN ADD CONSTRAINT fk_sitechan_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE SITECHAN ADD CONSTRAINT fk_sitechan_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE SNR_PHASE ADD CONSTRAINT fk_snr_phase_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE SNR_PHASE ADD CONSTRAINT fk_snr_phase_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE STAMAG ADD CONSTRAINT fk_stamag_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE STAMAG ADD CONSTRAINT fk_stamag_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE STAMAG ADD CONSTRAINT fk_stamag_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE STAMAG ADD CONSTRAINT fk_stamag_evid FOREIGN KEY (EVID) REFERENCES BULLETIN_RELEASE (EVID);

ALTER TABLE STANET ADD CONSTRAINT fk_stanet_net FOREIGN KEY (NET) REFERENCES AFFILIATION (NET);

ALTER TABLE STANET ADD CONSTRAINT fk_stanet_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE STAQUAL_DNAMES ADD CONSTRAINT fk_staqual_dnames_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE STATION_QUALITY ADD CONSTRAINT fk_station_quality_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE STAYIELD ADD CONSTRAINT fk_stayield_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE STAYIELD ADD CONSTRAINT fk_stayield_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE STAYIELD ADD CONSTRAINT fk_stayield_orid FOREIGN KEY (ORID) REFERENCES AR_INFO (ORID);

ALTER TABLE STAYIELD ADD CONSTRAINT fk_stayield_arid FOREIGN KEY (ARID) REFERENCES AMP3C (ARID);

ALTER TABLE SVDDISC ADD CONSTRAINT fk_svddisc_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE SVDDISC_CHAN_ORDER ADD CONSTRAINT fk_svddisc_chan_order_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE SVDDISC_CHAN_ORDER ADD CONSTRAINT fk_svddisc_chan_order_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE WFAUDIT ADD CONSTRAINT fk_wfaudit_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE WFAUDIT ADD CONSTRAINT fk_wfaudit_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE WFCONV ADD CONSTRAINT fk_wfconv_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE WFCONV ADD CONSTRAINT fk_wfconv_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE WFDISC ADD CONSTRAINT fk_wfdisc_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE WFDISC ADD CONSTRAINT fk_wfdisc_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE WFDISC ADD CONSTRAINT fk_wfdisc_wfid FOREIGN KEY (WFID) REFERENCES BEAM (WFID);

ALTER TABLE WFFILE ADD CONSTRAINT fk_wffile_sta FOREIGN KEY (STA) REFERENCES AFFILIATION (STA);

ALTER TABLE WFFILE ADD CONSTRAINT fk_wffile_chan FOREIGN KEY (CHAN) REFERENCES AMPLITUDE (CHAN);

ALTER TABLE WFTAG ADD CONSTRAINT fk_wftag_wfid FOREIGN KEY (WFID) REFERENCES BEAM (WFID);

