-- USNDC Complete Table Definitions (without foreign keys)
-- Extracted 177 tables

CREATE TABLE ACTIVE_ID (
    TAGNAME VARCHAR(8),,
    TAGID BIGINT,,
    CLIENT_INFO VARCHAR(64),,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE AFFILIATION (
    NET VARCHAR(8),,
    STA VARCHAR(6),,
    TIME DOUBLE PRECISION,,
    ENDTIME DOUBLE PRECISION,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_affiliation PRIMARY KEY (NET, STA, TIME)
);

CREATE TABLE ALGORITHM (
    ALGORITHM_ID BIGINT,,
    ALGORITHM_NAME VARCHAR(64),,
    DESCRIPTION VARCHAR(4000),,
    ON_DATE TIMESTAMP,,
    OFF_DATE TIMESTAMP,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_algorithm PRIMARY KEY (ALGORITHM_ID)
);

CREATE TABLE ALPHASITE (
    STA VARCHAR(6),,
    ADDRESS VARCHAR(16),,
    PREFDLID BIGINT,,
    PREFPORT INTEGER,,
    CON_ALLOWED VARCHAR(1),,
    DLID BIGINT,,
    TIME DOUBLE PRECISION,,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE AMP3C (
    ARID BIGINT,,
    CFREQ REAL,,
    VAMP REAL,,
    VSNR REAL,,
    HAMP REAL,,
    HSNR REAL,,
    HTOV REAL,,
    RID VARCHAR(8),,
    LDDATE TIMESTAMP
);

CREATE TABLE AMPDESCRIPT (
    AMPTYPE VARCHAR(8),,
    TOFF REAL,,
    TLEN REAL,,
    GVLO REAL,,
    GVHI REAL,,
    MTYPE VARCHAR(8),,
    AMPDESCR VARCHAR(255),,
    LDDATE TIMESTAMP
);

CREATE TABLE AMPLITUDE (
    AMPID BIGINT,,
    ARID BIGINT,,
    PARID BIGINT,,
    CHAN VARCHAR(8),,
    AMP REAL,,
    PER REAL,,
    SNR REAL,,
    AMPTIME DOUBLE PRECISION,,
    TIME DOUBLE PRECISION,,
    DURATION REAL,,
    DELTAF REAL,,
    AMPTYPE VARCHAR(8),,
    UNITS VARCHAR(15),,
    CLIP VARCHAR(1),,
    INARRIVAL VARCHAR(1),,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_amplitude PRIMARY KEY (AMPID)
);

CREATE TABLE AMPLITUDE_DYN_PARS_DBL (
    AMPID BIGINT,,
    GROUP_NAME VARCHAR(48),,
    PARAM_NAME VARCHAR(48),,
    D_VALUE DOUBLE PRECISION,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_amplitude_dyn_pars_dbl PRIMARY KEY (AMPID)
);

CREATE TABLE AMPLITUDE_DYN_PARS_INT (
    AMPID BIGINT,,
    GROUP_NAME VARCHAR(48),,
    PARAM_NAME VARCHAR(48),,
    I_VALUE BIGINT,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_amplitude_dyn_pars_int PRIMARY KEY (AMPID)
);

CREATE TABLE AMPLITUDE_DYN_PARS_STR (
    AMPID BIGINT,,
    GROUP_NAME VARCHAR(48),,
    PARAM_NAME VARCHAR(48),,
    S_VALUE VARCHAR(1024),,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_amplitude_dyn_pars_str PRIMARY KEY (AMPID)
);

CREATE TABLE AOI (
    LAT DOUBLE PRECISION,,
    LON DOUBLE PRECISION,,
    AOI_GEOCHAR VARCHAR(1),,
    LFAOI_GEOCHAR VARCHAR(1),,
    DEPTH_GEOCHAR VARCHAR(1),,
    SEISMIC_GEOCHAR VARCHAR(1),,
    TERRAIN_GEOCHAR VARCHAR(1),,
    ONDATE INTEGER,,
    OFFDATE INTEGER,,
    LDDATE TIMESTAMP
);

CREATE TABLE APMA (
    PHASE VARCHAR(8),,
    ARID BIGINT,,
    FREQ REAL,,
    SNR REAL,,
    AMPP REAL,,
    AMPS REAL,,
    AMPLR REAL,,
    RECT REAL,,
    PLANS REAL,,
    PLANLR REAL,,
    HVRATP REAL,,
    HVRAT REAL,,
    HMXMN REAL,,
    INANG3 REAL,,
    SEAZP REAL,,
    SEAZS REAL,,
    SEAZLR REAL,,
    INANG1 REAL,,
    PPHASETIME DOUBLE PRECISION,,
    SPHASETIME DOUBLE PRECISION,,
    AUTH VARCHAR(15),,
    APMARID BIGINT,,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE ARRIVAL (
    STA VARCHAR(6),,
    TIME DOUBLE PRECISION,,
    ARID BIGINT,,
    JDATE INTEGER,,
    STASSID BIGINT,,
    CHANID BIGINT,,
    CHAN VARCHAR(8),,
    IPHASE VARCHAR(8),,
    STYPE VARCHAR(1),,
    DELTIM REAL,,
    AZIMUTH REAL,,
    DELAZ REAL,,
    SLOW REAL,,
    DELSLO REAL,,
    EMA REAL,,
    RECT REAL,,
    AMP REAL,,
    PER REAL,,
    LOGAT REAL,,
    CLIP VARCHAR(1),,
    FM VARCHAR(2),,
    SNR REAL,,
    QUAL VARCHAR(1),,
    AUTH VARCHAR(15),,
    COMMID BIGINT,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_arrival PRIMARY KEY (ARID)
);

CREATE TABLE ARRIVAL_DYN_PARS_DBL (
    ARID BIGINT,,
    GROUP_NAME VARCHAR(48),,
    PARAM_NAME VARCHAR(48),,
    D_VALUE DOUBLE PRECISION,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_arrival_dyn_pars_dbl PRIMARY KEY (ARID)
);

CREATE TABLE ARRIVAL_DYN_PARS_INT (
    ARID BIGINT,,
    GROUP_NAME VARCHAR(48),,
    PARAM_NAME VARCHAR(48),,
    I_VALUE BIGINT,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_arrival_dyn_pars_int PRIMARY KEY (ARID)
);

CREATE TABLE ARRIVAL_DYN_PARS_STR (
    ARID BIGINT,,
    GROUP_NAME VARCHAR(48),,
    PARAM_NAME VARCHAR(48),,
    S_VALUE VARCHAR(1024),,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_arrival_dyn_pars_str PRIMARY KEY (ARID)
);

CREATE TABLE ARRIVAL_TAG (
    ARID BIGINT,,
    PROCESS_MODE VARCHAR(32),,
    PROCESS_ATTRIBUTE VARCHAR(32),,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_arrival_tag PRIMARY KEY (ARID)
);

CREATE TABLE AR_INFO (
    ORID BIGINT,,
    ARID BIGINT,,
    TIME_ERROR_CODE INTEGER,,
    AZ_ERROR_CODE INTEGER,,
    SLOW_ERROR_CODE INTEGER,,
    SRC_DPNT_CORR_TYPE INTEGER,,
    VMODEL VARCHAR(16),,
    TOTAL_TRAVEL_TIME REAL,,
    TT_TABLE_VALUE REAL,,
    ELLIP_CORR REAL,,
    ELEV_CORR REAL,,
    BULK_STATIC_STA_CORR REAL,,
    TT_SRC_DPNT_CORR REAL,,
    TT_MODEL_ERROR REAL,,
    TT_MEAS_ERROR REAL,,
    TT_MODEL_PLUS_MEAS_ERROR REAL,,
    AZ_SRC_DPNT_CORR REAL,,
    AZ_MODEL_ERROR REAL,,
    AZ_MEAS_ERROR REAL,,
    AZ_MODEL_PLUS_MEAS_ERROR REAL,,
    SL_SRC_DPNT_CORR REAL,,
    SL_MODEL_ERROR REAL,,
    SL_MEAS_ERROR REAL,,
    SL_MODEL_PLUS_MEAS_ERROR REAL,,
    TIME_IMPORT REAL,,
    AZ_IMPORT REAL,,
    SLOW_IMPORT REAL,,
    SLOW_VEC_RES REAL,,
    LDDATE TIMESTAMP
);

CREATE TABLE ASSOC (
    ARID BIGINT,,
    ORID BIGINT,,
    STA VARCHAR(6),,
    PHASE VARCHAR(8),,
    BELIEF REAL,,
    DELTA REAL,,
    SEAZ REAL,,
    ESAZ REAL,,
    TIMERES REAL,,
    TIMEDEF VARCHAR(1),,
    AZRES REAL,,
    AZDEF VARCHAR(1),,
    SLORES REAL,,
    SLODEF VARCHAR(1),,
    EMARES REAL,,
    WGT REAL,,
    VMODEL VARCHAR(15),,
    COMMID BIGINT,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_assoc PRIMARY KEY (ARID, ORID)
);

CREATE TABLE ASSOC_GA (
    ARID BIGINT,,
    ORID BIGINT,,
    STA VARCHAR(6),,
    PHASE VARCHAR(8),,
    BELIEF REAL,,
    DELTA REAL,,
    SEAZ REAL,,
    ESAZ REAL,,
    TIMERES REAL,,
    TIMEDEF VARCHAR(1),,
    AZRES REAL,,
    AZDEF VARCHAR(1),,
    SLORES REAL,,
    SLODEF VARCHAR(1),,
    EMARES REAL,,
    WGT REAL,,
    VMODEL VARCHAR(15),,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE ASSOC_GA_DEL (
    ARID BIGINT,,
    ORID BIGINT,,
    STA VARCHAR(6),,
    PHASE VARCHAR(8),,
    BELIEF REAL,,
    DELTA REAL,,
    SEAZ REAL,,
    ESAZ REAL,,
    TIMERES REAL,,
    TIMEDEF VARCHAR(1),,
    AZRES REAL,,
    AZDEF VARCHAR(1),,
    SLORES REAL,,
    SLODEF VARCHAR(1),,
    EMARES REAL,,
    WGT REAL,,
    VMODEL VARCHAR(15),,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE BEAM (
    WFID BIGINT,,
    FILTERID BIGINT,,
    AZIMUTH REAL,,
    SLOW REAL,,
    DESCRIP VARCHAR(50),,
    LDDATE TIMESTAMP
);

CREATE TABLE BULLETIN_RELEASE (
    ERPID BIGINT,,
    ORID BIGINT,,
    EVID BIGINT,,
    MAGID BIGINT,,
    AOI_GEOCHAR VARCHAR(1),,
    CLASSIFICATION_COMMENTS VARCHAR(4000),,
    CLASSIFICATION_RESULTS VARCHAR(4000),,
    GRNAME VARCHAR(40),,
    RELEASE_STATUS VARCHAR(16),,
    AUTH VARCHAR(15),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE BULLETIN_RELEASE_EXPORT (
    ERP_SEQ BIGINT,,
    MAX_ERPID BIGINT,,
    AUTH VARCHAR(15),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE BUTTERWORTH_FILTER (
    FILTERID BIGINT,,
    FILTER_TYPE VARCHAR(16),,
    FILTER_ORDER SMALLINT,,
    FILTER_LOW REAL,,
    FILTER_HIGH REAL,,
    FILTER_ZEROPH SMALLINT,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE CHANNAME (
    EXTERN_STA VARCHAR(6),,
    EXTERN_CHAN VARCHAR(8),,
    EXTERN_AUTH VARCHAR(20),,
    INTERN_STA VARCHAR(6),,
    INTERN_CHAN VARCHAR(8),,
    INTERN_CHANID BIGINT,,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE CHAN_GROUPS (
    CLASS VARCHAR(16),,
    NAME VARCHAR(20),,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    DURATION REAL,,
    INWFACTIVITY SMALLINT,,
    ONDATE INTEGER,,
    OFFDATE INTEGER,,
    LDDATE TIMESTAMP
);

CREATE TABLE CLASSIFICATION (
    CLASSIFICATION_ID BIGINT,,
    DESCRIPTION VARCHAR(64),,
    CLASS_LEVEL_ID BIGINT,,
    CLASS_DISSEM_ID BIGINT,,
    CLASS_DERIVED_ID BIGINT,,
    CLASS_DECLASS_ID BIGINT,,
    CLASS_REFER_ID BIGINT,,
    CLASS_OPR_ID BIGINT,,
    ON_DATE TIMESTAMP,,
    OFF_DATE TIMESTAMP,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP,,
    MODDATE TIMESTAMP
);

CREATE TABLE CLASSIFICATION_LEVEL (
    CLASS_LEVEL_ID BIGINT,,
    CLASS_LEVEL VARCHAR(64),,
    PARAGRAPH_MARK VARCHAR(16),,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE CLASSIFICATION_LOOKUP (
    CLASS_LOOKUP_ID BIGINT,,
    APPLICATION VARCHAR(64),,
    CLASSIFICATION_ID BIGINT,,
    ON_DATE TIMESTAMP,,
    OFF_DATE TIMESTAMP,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP,,
    MODDATE TIMESTAMP
);

CREATE TABLE CLASSIFICATION_OPR (
    CLASS_OPR_ID BIGINT,,
    CLASS_OPR VARCHAR(64),,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE CLASSIFICATION_REFER_TO (
    CLASS_REFER_ID BIGINT,,
    CLASS_REFER VARCHAR(4000),,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE CLASS_DECLASS_ID (
    CLASS_DECLASS_ID BIGINT,,
    CLASS_DECLASS VARCHAR(4000),,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE CLASS_DERIVED_ID (
    CLASS_DERIVED_ID BIGINT,,
    CLASS_DERIVED VARCHAR(4000),,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE CLASS_DISSEM_ID (
    CLASS_DISSEM_ID BIGINT,,
    CLASS_DISSEM VARCHAR(64),,
    PARAGRAPH_MARK VARCHAR(16),,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE CLUSTER_INFO (
    CLUID BIGINT,,
    DESCRIP VARCHAR(50),,
    PREFOR BIGINT,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE CLUSTER_MAGREF (
    CLUSTAID BIGINT,,
    ACTIVETIME DOUBLE PRECISION,,
    ORID BIGINT,,
    AMPTYPE VARCHAR(8),,
    MTYPE VARCHAR(15),,
    MVALUE REAL,,
    FILTERID BIGINT,,
    LEAD REAL,,
    DURATION REAL,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE CLUSTER_MEC (
    CLUSTAID BIGINT,,
    STA VARCHAR(6),,
    PHASE VARCHAR(8),,
    ACTIVETIME DOUBLE PRECISION,,
    CORR_TYPE VARCHAR(16),,
    CORRECTION REAL,,
    UNCERTAINTY REAL,,
    ONDATE INTEGER,,
    OFFDATE INTEGER,,
    TOTAL_EVENTS SMALLINT
);

CREATE TABLE CLUSTER_ORID (
    CLUSTAID BIGINT,,
    ORID BIGINT,,
    ACTIVETIME DOUBLE PRECISION,,
    LDDATE TIMESTAMP
);

CREATE TABLE CLUSTER_OVERRIDE (
    CLUSTAID BIGINT,,
    ACTIVETIME DOUBLE PRECISION,,
    THRESHOLD REAL,,
    SSD_DIMENSION INTEGER,,
    SVD_LEAD REAL,,
    MIN_DETECTION_INTERVAL REAL,,
    PREFPHASE VARCHAR(16),,
    LEAD REAL,,
    LAG REAL,,
    BEST_EVENT_MATCH_MULTIPLE REAL,,
    PHASE_ONSET_MULTIPLE REAL,,
    DET_TRACE_TRIM_MULTIPLE REAL,,
    CHANNEL_MASKING_THRESHOLD REAL,,
    PFA REAL,,
    THRESHOLD_PERCENT_OVERLAP INTEGER,,
    PHASE_SPECIFIC_OVERRIDE_REC VARCHAR(32),,
    MAX_DELAZ REAL,,
    MAX_DELSLOW REAL,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE CLUSTER_PHASE_OVERRIDE (
    CLUSTAID BIGINT,,
    ACTIVETIME DOUBLE PRECISION,,
    PHASE_SPECIFIC_OVERRIDE_REC VARCHAR(32),,
    PHASE VARCHAR(8),,
    LEAD REAL,,
    LAG REAL,,
    FLO REAL,,
    FHI REAL,,
    MAXADJ REAL,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE CLUSTER_STATION (
    CLUSTAID BIGINT,,
    ACTIVETIME DOUBLE PRECISION,,
    CLUID BIGINT,,
    STA VARCHAR(6),,
    MAX_DELAZ REAL,,
    MAX_DELSLOW REAL,,
    SSD_DIMENSION INTEGER,,
    SVD_LEAD REAL,,
    SVD_LAG REAL,,
    PREFPHASE VARCHAR(16),,
    LEAD REAL,,
    LAG REAL,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE CLUSTER_THRESHOLD (
    CLUSTAID BIGINT,,
    DETECTOR_TYPE VARCHAR(16),,
    SSD_DIMENSION INTEGER,,
    ACTIVETIME DOUBLE PRECISION,,
    ORID BIGINT,,
    THRESHOLD REAL,,
    PFA REAL,,
    OVERLAP INTEGER,,
    CHANNEL_MASKING_THRESHOLD REAL,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE CODAMAG_INPUT (
    AMPID BIGINT,,
    FLO REAL,,
    FHI REAL,,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    ORID BIGINT,,
    ARID BIGINT,,
    AMPDEF VARCHAR(1),,
    DELTA REAL,,
    BWRATIO REAL,,
    SAMPRATE REAL,,
    ENVSLOW REAL,,
    HWIDE REAL,,
    POLYID BIGINT,,
    TIME DOUBLE PRECISION,,
    ENDTIME DOUBLE PRECISION,,
    NOISE_START_TIME DOUBLE PRECISION,,
    NOISE_END_TIME DOUBLE PRECISION,,
    TMEAS DOUBLE PRECISION,,
    SHAPE_SPREADING REAL,,
    SHAPE_DECAY REAL,,
    SHAPEDMIN REAL,,
    SHAPEDMAX REAL,,
    PEAK_VELOCITY REAL,,
    VGDMIN REAL,,
    VGDMAX REAL,,
    PATH_COR_TYPE VARCHAR(8),,
    PATH_COR REAL,,
    SITE_COR REAL,,
    SITEUNIT VARCHAR(9),,
    WMODEL_NAME VARCHAR(50),,
    YINTERCEPT REAL,,
    YSLOPE REAL,,
    FFACTOR REAL,,
    SRC_REGION VARCHAR(50),,
    MBINTERCEPT REAL,,
    MBSLOPE REAL,,
    MBSIGMA REAL,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE CODAMAG_OUTPUT (
    AMPID BIGINT,,
    FLO REAL,,
    FHI REAL,,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    ORID BIGINT,,
    ARID BIGINT,,
    DELTA REAL,,
    RAW_AMP REAL,,
    UNCERTAINTY REAL,,
    NOISE_AMP REAL,,
    AMPCOR REAL,,
    AMP_WGT REAL,,
    MB_CODA REAL,,
    YIELD REAL,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE CONTINUOUS_DATA_STATUS (
    STATUS_ID BIGINT,,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    INDICATOR VARCHAR(64),,
    START_DATE TIMESTAMP,,
    END_DATE TIMESTAMP,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE DATAUSER (
    USERID BIGINT,,
    POCID BIGINT,,
    USERNAME VARCHAR(24),,
    DOMAIN VARCHAR(48),,
    MSGTYPE VARCHAR(16),,
    USERSTATUS VARCHAR(24),,
    PRIORITY SMALLINT,,
    COMMID BIGINT,,
    EMAILLIMIT INTEGER,,
    SERVICETIME DOUBLE PRECISION,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_datauser PRIMARY KEY (USERNAME)
);

CREATE TABLE DA_INTERVAL (
    INTVLID BIGINT,,
    CLASS VARCHAR(16),,
    NAME VARCHAR(20),,
    TIME DOUBLE PRECISION,,
    ENDTIME DOUBLE PRECISION,,
    STATE VARCHAR(16),,
    AUTH VARCHAR(15),,
    PERCENT_AVAILABLE DOUBLE PRECISION,,
    PROC_START_DATE TIMESTAMP,,
    PROC_END_DATE TIMESTAMP,,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE DA_REFSTA_LATENCY (
    LATENCY_ID BIGINT,,
    STA VARCHAR(6),,
    INTERVAL_START_TIME TIMESTAMP,,
    INTERVAL_END_TIME TIMESTAMP,,
    MIN_LATENCY_SECS DOUBLE PRECISION,,
    MAX_LATENCY_SECS DOUBLE PRECISION,,
    TOTAL_SECS DOUBLE PRECISION,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE DA_REFSTA_SUMMARY (
    SUMMARY_ID BIGINT,,
    STA VARCHAR(6),,
    INTERVAL_START_TIME TIMESTAMP,,
    INTERVAL_END_TIME TIMESTAMP,,
    PERCENT DOUBLE PRECISION,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE DA_SITECHAN_LATENCY (
    LATENCY_ID BIGINT,,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    INTERVAL_START_TIME TIMESTAMP,,
    INTERVAL_END_TIME TIMESTAMP,,
    MIN_LATENCY_SECS DOUBLE PRECISION,,
    MAX_LATENCY_SECS DOUBLE PRECISION,,
    TOTAL_SECS DOUBLE PRECISION,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE DECONVOLUTION (
    DECONID BIGINT,,
    TYPE VARCHAR(16),,
    LOWCUTFRAC REAL,,
    LOWPASSFREQ REAL,,
    HIGHCUTFRAC REAL,,
    HIGHPASSFREQ REAL,,
    WATERLEVEL REAL,,
    FINALUNITS VARCHAR(1),,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE DEFINING_OBSTYPES (
    OBSTYPE_ID BIGINT,,
    CLASS VARCHAR(16),,
    TYPE VARCHAR(10),,
    DESCRIPTION VARCHAR(4000),,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE DEFINING_RULES (
    RULE_ID BIGINT,,
    NET VARCHAR(8),,
    REFSTA VARCHAR(6),,
    SITE VARCHAR(6),,
    PHASE VARCHAR(8),,
    OBSTYPE_ID BIGINT,,
    VALUE_ID BIGINT,,
    ON_DATE TIMESTAMP,,
    OFF_DATE TIMESTAMP,,
    AUTHOR VARCHAR(64),,
    PRIORITY INTEGER,,
    COMMENTS VARCHAR(4000),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE DEFINING_VALUES (
    VALUE_ID BIGINT,,
    VALUE VARCHAR(1),,
    DESCRIPTION VARCHAR(4000),,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE DETECTION (
    ARID BIGINT,,
    JDATE INTEGER,,
    TIME DOUBLE PRECISION,,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    BMTYP VARCHAR(4),,
    SPROID BIGINT,,
    CFREQ REAL,,
    SEAZ REAL,,
    DELAZ REAL,,
    SLOW REAL,,
    DELSLO REAL,,
    SNR REAL,,
    STAV REAL,,
    FSTAT REAL,,
    DELTIM REAL,,
    BANDW REAL,,
    FKQUAL SMALLINT,,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE DETECTION_THRESHOLD (
    CLUSTAID BIGINT,,
    ORID BIGINT,,
    DETECTOR_TYPE VARCHAR(16),,
    TIME DOUBLE PRECISION,,
    ENDTIME DOUBLE PRECISION,,
    THRESHOLD REAL,,
    NUM_DETECTIONS INTEGER,,
    STA VARCHAR(6),,
    PFA REAL,,
    OVERLAP INTEGER,,
    CHANNEL_MASKING_THRESHOLD REAL,,
    SSD_DIMENSION INTEGER,,
    DOF REAL,,
    DATA_MASKED INTEGER,,
    TOTAL_DATA INTEGER,,
    DESCRIPT VARCHAR(100),,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE DISCRIMUSE (
    ORID BIGINT,,
    DISCRIMTYPE VARCHAR(10),,
    STA VARCHAR(6),,
    DISCRIM_FLAG VARCHAR(1),,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE DISCRIMVOTE (
    ORID BIGINT,,
    DISCRIMTYPE VARCHAR(10),,
    STA VARCHAR(6),,
    VOTE VARCHAR(1),,
    COMMID BIGINT,,
    OVERRIDE INTEGER,,
    EVAL_COMMENT VARCHAR(22),,
    LDDATE TIMESTAMP
);

CREATE TABLE DISCRIM_PARAM (
    POLYID BIGINT,,
    AMPCOR_VERID BIGINT,,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    PARAMSETID BIGINT,,
    LOWCUTFRAC REAL,,
    MINLOWPASSFREQ REAL,,
    HIGHPASSFRAC REAL,,
    HIGHCUTFRAC REAL,,
    PNGV1 REAL,,
    PNGV2 REAL,,
    PNINT DOUBLE PRECISION,,
    PGGV1 REAL,,
    PGGV2 REAL,,
    PGINT DOUBLE PRECISION,,
    SNGV1 REAL,,
    SNGV2 REAL,,
    SNINT DOUBLE PRECISION,,
    LGGV1 REAL,,
    LGGV2 REAL,,
    LGINT DOUBLE PRECISION,,
    TFACTOR REAL,,
    TAPERWIDTH REAL,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE DLMAN (
    DLID BIGINT,,
    MACHINE VARCHAR(32),,
    RUNNING VARCHAR(1),,
    CONNMANPORT INTEGER,,
    CONTROLPORT INTEGER,,
    ARCHIVEPORT INTEGER,,
    FORWARDPORT INTEGER,,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE DOPPLER_DETECTION (
    DOPPLERID BIGINT,,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    EVENT_TIME DOUBLE PRECISION,,
    DURATION REAL,,
    SNR REAL,,
    AZIMUTH REAL,,
    ETYPE VARCHAR(7),,
    CFREQ REAL,,
    RANGE_MINFREQ REAL,,
    RANGE_MAXFREQ REAL,,
    TRACE_MINFREQ REAL,,
    TRACE_MAXFREQ REAL,,
    USE_AS_REFERENCE_EVENT VARCHAR(1),,
    FILTER_STRING VARCHAR(2000),,
    CONF REAL,,
    COMMENTS VARCHAR(4000),,
    INTERNAL_COMMENTS VARCHAR(4000),,
    ANALYST VARCHAR(32),,
    TIMESENT DOUBLE PRECISION,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE ECM_CHAN_AMPLITUDE (
    ORID BIGINT,,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    PHASE VARCHAR(8),,
    LFREQ DOUBLE PRECISION,,
    HFREQ DOUBLE PRECISION,,
    AMPCOR_VERID BIGINT,,
    TIME DOUBLE PRECISION,,
    ENDTIME DOUBLE PRECISION,,
    AMPRAW DOUBLE PRECISION,,
    AMPMDAC DOUBLE PRECISION,,
    AMPDAC DOUBLE PRECISION,,
    AMPMAC DOUBLE PRECISION,,
    NTIME DOUBLE PRECISION,,
    NENDTIME DOUBLE PRECISION,,
    SNR DOUBLE PRECISION,,
    AMPDEF VARCHAR(1),,
    AUTH VARCHAR(15),,
    COMMENTS VARCHAR(4000),,
    LDDATE TIMESTAMP
);

CREATE TABLE ECM_CONSTANT (
    NAME VARCHAR(30),,
    VALUE DOUBLE PRECISION,,
    LDDATE TIMESTAMP
);

CREATE TABLE ECM_COV (
    POLYID BIGINT,,
    COV_VERID BIGINT,,
    SOURCE_TYPE VARCHAR(15),,
    DISCRIM_NAME_1 VARCHAR(10),,
    DISCRIM_NAME_2 VARCHAR(10),,
    COVARIANCE DOUBLE PRECISION,,
    MEAN_1 DOUBLE PRECISION,,
    AUTH VARCHAR(15),,
    COMMENTS VARCHAR(4000),,
    LDDATE TIMESTAMP
);

CREATE TABLE ECM_DISCRIMINANTS (
    ORID BIGINT,,
    DISCRIM_NAME VARCHAR(15),,
    COV_VERID BIGINT,,
    DISCRIM_P_VALUE DOUBLE PRECISION,,
    DISCRIM_DEF VARCHAR(1),,
    EXPLANATION VARCHAR(4000),,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE ECM_EVENT_RESULTS (
    ORID BIGINT,,
    EVID BIGINT,,
    COV_VERID BIGINT,,
    RDA_VERID BIGINT,,
    CLASS_TYPE VARCHAR(15),,
    CLASS_TYPE_OVRD VARCHAR(15),,
    COMMENTS VARCHAR(4000),,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE ECM_REF_CHAN_AMPLITUDE (
    EVID BIGINT,,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    PHASE VARCHAR(8),,
    LFREQ DOUBLE PRECISION,,
    HFREQ DOUBLE PRECISION,,
    AMPCOR_VERID BIGINT,,
    POLYID BIGINT,,
    DELTA REAL,,
    TIME DOUBLE PRECISION,,
    ENDTIME DOUBLE PRECISION,,
    AMPRAW DOUBLE PRECISION,,
    AMPMDAC DOUBLE PRECISION,,
    AMPDAC DOUBLE PRECISION,,
    AMPMAC DOUBLE PRECISION,,
    NTIME DOUBLE PRECISION,,
    NENDTIME DOUBLE PRECISION,,
    SNR DOUBLE PRECISION,,
    AMPDEF VARCHAR(1),,
    AUTH VARCHAR(15),,
    COMMENTS VARCHAR(4000),,
    LDDATE TIMESTAMP
);

CREATE TABLE ECM_REF_DISCRIM (
    EVID BIGINT,,
    COV_VERID BIGINT,,
    DISCRIM_NAME VARCHAR(15),,
    DISCRIM_P_VALUE DOUBLE PRECISION,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE ECM_REF_EVENT (
    EVID BIGINT,,
    TIME DOUBLE PRECISION,,
    LAT DOUBLE PRECISION,,
    LON DOUBLE PRECISION,,
    DEPTH REAL,,
    MB REAL,,
    MS REAL,,
    MW REAL,,
    SOURCE_TYPE VARCHAR(7),,
    SUB_TYPE VARCHAR(10),,
    POLYID BIGINT,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE ECM_REGION_PREF_VERSION (
    POLYID BIGINT,,
    COV_VERID BIGINT,,
    RDA_VERID BIGINT,,
    AUTH VARCHAR(15),,
    COMMENTS VARCHAR(4000),,
    LDDATE TIMESTAMP
);

CREATE TABLE ECM_SOURCES (
    ORID BIGINT,,
    SOURCE_TYPE VARCHAR(15),,
    COV_VERID BIGINT,,
    RDA_VERID BIGINT,,
    POP_MEM DOUBLE PRECISION,,
    CON_PROB DOUBLE PRECISION,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE ECM_STA_PREF_VERSION (
    POLYID BIGINT,,
    STA VARCHAR(6),,
    AMPCOR_VERID BIGINT,,
    AUTH VARCHAR(15),,
    COMMENTS VARCHAR(4000),,
    LDDATE TIMESTAMP
);

CREATE TABLE ENVELOPE_CONTRIBUTION (
    FLO REAL,,
    FHI REAL,,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    ORID BIGINT,,
    ARID BIGINT,,
    AMPDEF VARCHAR(1),,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE EVENT (
    EVID BIGINT,,
    EVNAME VARCHAR(32),,
    PREFOR BIGINT,,
    AUTH VARCHAR(15),,
    COMMID BIGINT,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_event PRIMARY KEY (EVID)
);

CREATE TABLE EVENT_CONTROL (
    ORID BIGINT,,
    EVID BIGINT,,
    PREFER_LOC VARCHAR(1),,
    CONSTRAIN_OT SMALLINT,,
    CONSTRAIN_LATLON SMALLINT,,
    CONSTRAIN_DEPTH SMALLINT,,
    SRC_DPNT_CORR SMALLINT,,
    LOC_SRC_DPNT_REG VARCHAR(15),,
    LOC_SDV_SCREEN SMALLINT,,
    LOC_SDV_MULT REAL,,
    LOC_ALPHA_ONLY SMALLINT,,
    LOC_ALL_STAS SMALLINT,,
    LOC_DIST_VARWGT SMALLINT,,
    LOC_USER_VARWGT REAL,,
    MAG_SRC_DPNT_REG VARCHAR(15),,
    MAG_SDV_SCREEN SMALLINT,,
    MAG_SDV_MULT REAL,,
    MAG_ALPHA_ONLY SMALLINT,,
    MAG_ALL_STAS SMALLINT,,
    MB_MIN_DIST REAL,,
    MB_MAX_DIST REAL,,
    MMODEL VARCHAR(15),,
    COV_SM_AXES REAL,,
    COV_DEPTH_TIME REAL,,
    OBS_CORR_METHOD SMALLINT,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_event_control PRIMARY KEY (EVID)
);

CREATE TABLE EVENT_CORRELATION (
    CORR_ID BIGINT,,
    SOURCE_ORID BIGINT,,
    SOURCE_EVID BIGINT,,
    SOURCE_STARTTIME DOUBLE PRECISION,,
    SOURCE_SECS DOUBLE PRECISION,,
    REFERENCE_ORID BIGINT,,
    REFERENCE_EVID BIGINT,,
    REFERENCE_STARTTIME DOUBLE PRECISION,,
    REFERENCE_SECS DOUBLE PRECISION,,
    STA VARCHAR(6),,
    FILTER_STRING VARCHAR(2000),,
    NUM_CHAN INTEGER,,
    CHAN_LIST VARCHAR(2000),,
    CORR_COEF DOUBLE PRECISION,,
    CORR_TIME DOUBLE PRECISION,,
    SCAN_TYPE VARCHAR(32),,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE EVENT_QUALITY (
    EQID BIGINT,,
    ORID BIGINT,,
    EVQUAL REAL,,
    NETPROB REAL,,
    DETPROB REAL,,
    HISTPROB REAL,,
    NNDEF REAL,,
    NSMAJAX REAL,,
    NDELTA_STA REAL,,
    NTIMERES REAL,,
    NAZRES REAL,,
    NSLORES REAL,,
    NAMPRES REAL,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE FEEDBACK (
    FEEDBACK_ID BIGINT,,
    EVID BIGINT,,
    ORID BIGINT,,
    EVENT_TIME DOUBLE PRECISION,,
    TITLE VARCHAR(64),,
    ANALYST VARCHAR(32),,
    ACCOUNT VARCHAR(15),,
    FEEDBACK_ANALYST VARCHAR(32),,
    FEEDBACK_ACCOUNT VARCHAR(15),,
    RESPONSE VARCHAR(4000),,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE FEEDBACK_CATAFFILIATION (
    FBAFFILIATION_ID BIGINT,,
    FEEDBACK_ID BIGINT,,
    FBCATEGORY_ID BIGINT,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE FEEDBACK_CATEGORIES (
    FBCATEGORY_ID BIGINT,,
    TITLE VARCHAR(64),,
    DESCRIPTION VARCHAR(4000),,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE FEEDBACK_SCREENSHOTS (
    FBSCREENSHOT_ID BIGINT,,
    FEEDBACK_ID BIGINT,,
    TITLE VARCHAR(64),,
    DESCRIPTION VARCHAR(4000),,
    TYPE VARCHAR(10),,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE FEEDBACK_STATE (
    FBSTATE_ID BIGINT,,
    FEEDBACK_ID BIGINT,,
    FBSTATECATEGORY_ID BIGINT,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE FEEDBACK_STATE_CATEGORIES (
    FBSTATECATEGORY_ID BIGINT,,
    TITLE VARCHAR(64),,
    DESCRIPTION VARCHAR(4000),,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE FILTER (
    FILTERID BIGINT,,
    FILTER_METHOD VARCHAR(2),,
    FILTER_STRING VARCHAR(2000),,
    FILTER_HASH VARCHAR(2000),,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_filter PRIMARY KEY (FILTERID)
);

CREATE TABLE FILTER_COEFFICIENTS (
    FILTERID BIGINT,,
    VALUE_NAME VARCHAR(48),,
    COL_SEQ INTEGER,,
    D_VALUE DOUBLE PRECISION,,
    LDDATE TIMESTAMP
);

CREATE TABLE FILTER_GROUP (
    PARENT_FILTERID BIGINT,,
    CHILD_FILTERID BIGINT,,
    CHILD_SEQUENCE INTEGER,,
    LDDATE TIMESTAMP
);

CREATE TABLE FILTER_VALUES_DOUBLE (
    FILTERID BIGINT,,
    VALUE_NAME VARCHAR(48),,
    D_VALUE DOUBLE PRECISION,,
    LDDATE TIMESTAMP
);

CREATE TABLE FILTER_VALUES_INTEGER (
    FILTERID BIGINT,,
    VALUE_NAME VARCHAR(48),,
    I_VALUE BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE FILTER_VALUES_STRING (
    FILTERID BIGINT,,
    VALUE_NAME VARCHAR(48),,
    S_VALUE VARCHAR(1024),,
    LDDATE TIMESTAMP
);

CREATE TABLE FK_PROCESSING (
    ARID BIGINT,,
    PROCID BIGINT,,
    LEAD REAL,,
    LAG REAL,,
    FKFHI REAL,,
    FKFLO REAL,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE FTPFAILED (
    MSGID BIGINT,,
    FTP_ADDRESS VARCHAR(64),,
    NUMFAILEDATTEMPT SMALLINT,,
    LASTFAILEDTIME DOUBLE PRECISION,,
    FTPSTATUS VARCHAR(8),,
    LDDATE TIMESTAMP
);

CREATE TABLE FTPLOGIN (
    FTP_ADDRESS VARCHAR(64),,
    USERNAME VARCHAR(24),,
    PASSWORD VARCHAR(16),,
    LDDATE TIMESTAMP
);

CREATE TABLE GA_TAG (
    OBJTYPE VARCHAR(1),,
    ID BIGINT,,
    PROCESS_STATE VARCHAR(20),,
    LAT REAL,,
    LON REAL,,
    TIME DOUBLE PRECISION,,
    EVID_REJECT BIGINT,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE GREGION (
    GRN INTEGER,,
    GRNAME VARCHAR(40),,
    LDDATE TIMESTAMP
);

CREATE TABLE HISTORIC_INFO_CYLINDER (
    HISTORIC_INFO_CYLINDER_ID BIGINT,,
    LAT DOUBLE PRECISION,,
    LON DOUBLE PRECISION,,
    RADIUS REAL,,
    DEPTH REAL,,
    LOWER_DEPTH REAL,,
    UPPER_DEPTH REAL,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE HISTORIC_INFO_SHELL (
    HISTORIC_INFO_SHELL_ID BIGINT,,
    ALGORITHM_ID BIGINT,,
    LAT DOUBLE PRECISION,,
    LON DOUBLE PRECISION,,
    INNER_RADIUS REAL,,
    OUTER_RADIUS REAL,,
    DEPTH REAL,,
    LOWER_DEPTH REAL,,
    UPPER_DEPTH REAL,,
    MIN_AZIMUTH REAL,,
    MAX_AZIMUTH REAL,,
    REFSTA VARCHAR(6),,
    PHASE VARCHAR(8),,
    THRESHOLD REAL,,
    UNCERTAINTY REAL,,
    RELIABILITY REAL,,
    NUM_OBSERVATIONS INTEGER,,
    PROCESSING_MODE SMALLINT,,
    ON_DATE TIMESTAMP,,
    OFF_DATE TIMESTAMP,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE HISTORIC_INFO_STA_PHASE (
    HISTORIC_INFO_STA_PHASE_ID BIGINT,,
    HISTORIC_INFO_CYLINDER_ID BIGINT,,
    ALGORITHM_ID BIGINT,,
    REFSTA VARCHAR(6),,
    PHASE VARCHAR(8),,
    THRESHOLD REAL,,
    UNCERTAINTY REAL,,
    RELIABILITY REAL,,
    NUM_OBSERVATIONS INTEGER,,
    PROCESSING_MODE SMALLINT,,
    ON_DATE TIMESTAMP,,
    OFF_DATE TIMESTAMP,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE HYDRO_ARRIVAL (
    ARID BIGINT,,
    STA VARCHAR(6),,
    DURONSET DOUBLE PRECISION,,
    DUREND DOUBLE PRECISION,,
    ONSET_TIME DOUBLE PRECISION,,
    TERMINATION_TIME DOUBLE PRECISION,,
    CPLAG REAL,,
    BPFRQAC REAL,,
    RT REAL,,
    BPFRQCEP REAL,,
    RMS REAL,,
    FLT_RTO REAL,,
    NORMAMP REAL,,
    AMPCORCLIP REAL,,
    AMPCORDIST REAL,,
    AMPCORDEPTH REAL,,
    YIELD REAL,,
    YLDERR REAL,,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE HYDRO_ARR_GROUP (
    HYDRO_ID BIGINT,,
    AZ1 REAL,,
    AZ2 REAL,,
    SLOW REAL,,
    DELAZ REAL,,
    NHYDARR SMALLINT,,
    NET VARCHAR(8),,
    HYD_GRP_PHASE VARCHAR(8),,
    LDDATE TIMESTAMP
);

CREATE TABLE HYDRO_ASSOC (
    ARID BIGINT,,
    HYDRO_ID BIGINT,,
    AZCONTRIB VARCHAR(1),,
    LDDATE TIMESTAMP
);

CREATE TABLE HYDRO_ORIGIN (
    ORID BIGINT,,
    HYDROLOC_CODE INTEGER,,
    HYDROYIELD REAL,,
    HYDROYLDERR REAL,,
    NUM_IN_SERIES INTEGER,,
    SERID BIGINT,,
    HYD_CLASS_CODE INTEGER,,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE INSTRUMENT (
    INID BIGINT,,
    INSNAME VARCHAR(50),,
    INSTYPE VARCHAR(6),,
    BAND VARCHAR(1),,
    DIGITAL VARCHAR(1),,
    SAMPRATE REAL,,
    NCALIB REAL,,
    NCALPER REAL,,
    DIR VARCHAR(64),,
    DFILE VARCHAR(32),,
    RSPTYPE VARCHAR(6),,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_instrument PRIMARY KEY (INID)
);

CREATE TABLE INTERVAL (
    INTVLID BIGINT,,
    CLASS VARCHAR(16),,
    NAME VARCHAR(20),,
    TIME DOUBLE PRECISION,,
    ENDTIME DOUBLE PRECISION,,
    STATE VARCHAR(16),,
    AUTH VARCHAR(15),,
    PERCENT_AVAILABLE DOUBLE PRECISION,,
    PROC_START_DATE TIMESTAMP,,
    PROC_END_DATE TIMESTAMP,,
    MODDATE TIMESTAMP,,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE MDAC_FD (
    FDID BIGINT,,
    AMPCOR_VERID BIGINT,,
    CORRID BIGINT,,
    LFREQ REAL,,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    TOMOID BIGINT,,
    POLYID BIGINT,,
    A DOUBLE PRECISION,,
    B DOUBLE PRECISION,,
    C DOUBLE PRECISION,,
    SITEFACT DOUBLE PRECISION,,
    ALGOID BIGINT,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE MDAC_FI (
    CORRID BIGINT,,
    AMPCOR_VERID BIGINT,,
    POLYID BIGINT,,
    STA VARCHAR(6),,
    PHASE VARCHAR(8),,
    CHAN VARCHAR(8),,
    CORRNAME VARCHAR(32),,
    SIGMA DOUBLE PRECISION,,
    DELSIGMA DOUBLE PRECISION,,
    PSI REAL,,
    DELPSI REAL,,
    Q0 DOUBLE PRECISION,,
    DELQ0 DOUBLE PRECISION,,
    GAMMA REAL,,
    DELGAMMA REAL,,
    ZETA REAL,,
    M0_REF DOUBLE PRECISION,,
    U0 REAL,,
    ETA REAL,,
    DELETA REAL,,
    DISTCRIT DOUBLE PRECISION,,
    ALPHAS REAL,,
    BETAS REAL,,
    RHOS DOUBLE PRECISION,,
    ALPHAR REAL,,
    BETAR REAL,,
    RHOR DOUBLE PRECISION,,
    RADPATP REAL,,
    RADPATS REAL,,
    SNR1 DOUBLE PRECISION,,
    SNR2 DOUBLE PRECISION,,
    NOISETYPE VARCHAR(15),,
    MAGID BIGINT,,
    MAGTYPE VARCHAR(6),,
    ALGOID BIGINT,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE MSGAUX (
    MSGID BIGINT,,
    MSGROW SMALLINT,,
    STATECOUNT INTEGER,,
    COMMAND VARCHAR(24),,
    SUB_STATUS VARCHAR(24),,
    LDDATE TIMESTAMP
);

CREATE TABLE MSGDATATYPE (
    MSGID BIGINT,,
    MSGDTYPE VARCHAR(16),,
    MSGDFORMAT VARCHAR(16),,
    MSGSTATUS VARCHAR(32),,
    FOFF BIGINT,,
    MSIZE INTEGER,,
    LDDATE TIMESTAMP
);

CREATE TABLE MSGDEST (
    MSGDID BIGINT,,
    MSGID BIGINT,,
    TRANSMETH VARCHAR(16),,
    EMAILTO VARCHAR(64),,
    MSGSTATUS VARCHAR(32),,
    ITIME DOUBLE PRECISION,,
    TIMESENT DOUBLE PRECISION,,
    LDDATE TIMESTAMP
);

CREATE TABLE MSGDISC (
    MSGID BIGINT,,
    USERID BIGINT,,
    MSGVER VARCHAR(8),,
    MSGTYPE VARCHAR(16),,
    SUBTYPE VARCHAR(20),,
    EXTMSGID VARCHAR(20),,
    INTID BIGINT,,
    INTIDTYPE VARCHAR(16),,
    MSGSRC VARCHAR(16),,
    ITIME DOUBLE PRECISION,,
    IDATE INTEGER,,
    IMETHOD VARCHAR(8),,
    ISRC VARCHAR(64),,
    MSIZE INTEGER,,
    MSGSTATUS VARCHAR(32),,
    SUBJECT VARCHAR(64),,
    DIR VARCHAR(64),,
    DFILE VARCHAR(32),,
    FOFF BIGINT,,
    MFOFF INTEGER,,
    FILEOFF INTEGER,,
    FILESIZE INTEGER,,
    SIGTYPE VARCHAR(64),,
    VERIFSTATUS VARCHAR(4),,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE MSVMAX_DESCRIPT (
    AMPID BIGINT,,
    STA VARCHAR(6),,
    ORID BIGINT,,
    ARID BIGINT,,
    HIGH_SNR_COUNT SMALLINT,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE MSVMAX_RESULTS (
    AMPID BIGINT,,
    PER REAL,,
    MEASTYPE VARCHAR(1),,
    AMP REAL,,
    AMPTIME DOUBLE PRECISION,,
    INS_RESPONSE REAL,,
    AMPCOR REAL,,
    MAGNITUDE REAL,,
    UNCERTAINTY REAL,,
    TIME DOUBLE PRECISION,,
    ENDTIME DOUBLE PRECISION,,
    LDDATE TIMESTAMP
);

CREATE TABLE NETMAG (
    MAGID BIGINT,,
    NET VARCHAR(8),,
    ORID BIGINT,,
    EVID BIGINT,,
    MAGTYPE VARCHAR(6),,
    NSTA INTEGER,,
    MAGNITUDE REAL,,
    UNCERTAINTY REAL,,
    AUTH VARCHAR(15),,
    COMMID BIGINT,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_netmag PRIMARY KEY (MAGID)
);

CREATE TABLE NETWORK (
    NETWORKID BIGINT,,
    NET VARCHAR(8),,
    NETWORK_NAME VARCHAR(32),,
    DESCRIPTION VARCHAR(4000),,
    NETWORK_TYPE VARCHAR(15),,
    ON_DATE TIMESTAMP,,
    OFF_DATE TIMESTAMP,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE NETYIELD (
    YIELDID BIGINT,,
    NET VARCHAR(8),,
    ORID BIGINT,,
    EVID BIGINT,,
    YIELD REAL,,
    NSTA INTEGER,,
    FFACTOR REAL,,
    WMODEL_NAME VARCHAR(50),,
    AUTH VARCHAR(15),,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE NET_CODA_SPECTRUM (
    MAGID BIGINT,,
    FREQ REAL,,
    AMPCOR REAL,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE OMITTED_CHANNELS (
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    TIME DOUBLE PRECISION,,
    ENDTIME DOUBLE PRECISION,,
    COMMID BIGINT,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE ORIGERR (
    ORID BIGINT,,
    SXX REAL,,
    SYY REAL,,
    SZZ REAL,,
    STT REAL,,
    SXY REAL,,
    SXZ REAL,,
    SYZ REAL,,
    STX REAL,,
    STY REAL,,
    STZ REAL,,
    SDOBS REAL,,
    SMAJAX REAL,,
    SMINAX REAL,,
    STRIKE REAL,,
    SDEPTH REAL,,
    STIME REAL,,
    CONF REAL,,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE ORIGERR_GA (
    ORID BIGINT,,
    SXX REAL,,
    SYY REAL,,
    SZZ REAL,,
    STT REAL,,
    SXY REAL,,
    SXZ REAL,,
    SYZ REAL,,
    STX REAL,,
    STY REAL,,
    STZ REAL,,
    SDOBS REAL,,
    SMAJAX REAL,,
    SMINAX REAL,,
    STRIKE REAL,,
    SDEPTH REAL,,
    STIME REAL,,
    CONF REAL,,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE ORIGERR_GA_DEL (
    ORID BIGINT,,
    SXX REAL,,
    SYY REAL,,
    SZZ REAL,,
    STT REAL,,
    SXY REAL,,
    SXZ REAL,,
    SYZ REAL,,
    STX REAL,,
    STY REAL,,
    STZ REAL,,
    SDOBS REAL,,
    SMAJAX REAL,,
    SMINAX REAL,,
    STRIKE REAL,,
    SDEPTH REAL,,
    STIME REAL,,
    CONF REAL,,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE ORIGIN (
    LAT REAL,,
    LON REAL,,
    DEPTH REAL,,
    TIME DOUBLE PRECISION,,
    ORID BIGINT,,
    EVID BIGINT,,
    JDATE INTEGER,,
    NASS SMALLINT,,
    NDEF SMALLINT,,
    NDP SMALLINT,,
    GRN INTEGER,,
    SRN INTEGER,,
    ETYPE VARCHAR(7),,
    DEPDP REAL,,
    DTYPE VARCHAR(1),,
    MB REAL,,
    MBID BIGINT,,
    MS REAL,,
    MSID BIGINT,,
    ML REAL,,
    MLID BIGINT,,
    ALGORITHM VARCHAR(15),,
    AUTH VARCHAR(15),,
    COMMID BIGINT,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_origin PRIMARY KEY (ORID)
);

CREATE TABLE ORIGIN_GA (
    LAT REAL,,
    LON REAL,,
    DEPTH REAL,,
    TIME DOUBLE PRECISION,,
    ORID BIGINT,,
    EVID BIGINT,,
    JDATE INTEGER,,
    NASS SMALLINT,,
    NDEF SMALLINT,,
    NDP SMALLINT,,
    GRN INTEGER,,
    SRN INTEGER,,
    ETYPE VARCHAR(7),,
    DEPDP REAL,,
    DTYPE VARCHAR(1),,
    MB REAL,,
    MBID BIGINT,,
    MS REAL,,
    MSID BIGINT,,
    ML REAL,,
    MLID BIGINT,,
    ALGORITHM VARCHAR(15),,
    AUTH VARCHAR(15),,
    COMMID BIGINT,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_origin_ga PRIMARY KEY (ORID)
);

CREATE TABLE ORIGIN_GA_DEL (
    LAT REAL,,
    LON REAL,,
    DEPTH REAL,,
    TIME DOUBLE PRECISION,,
    ORID BIGINT,,
    EVID BIGINT,,
    JDATE INTEGER,,
    NASS SMALLINT,,
    NDEF SMALLINT,,
    NDP SMALLINT,,
    GRN INTEGER,,
    SRN INTEGER,,
    ETYPE VARCHAR(7),,
    DEPDP REAL,,
    DTYPE VARCHAR(1),,
    MB REAL,,
    MBID BIGINT,,
    MS REAL,,
    MSID BIGINT,,
    ML REAL,,
    MLID BIGINT,,
    ALGORITHM VARCHAR(15),,
    AUTH VARCHAR(15),,
    COMMID BIGINT,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_origin_ga_del PRIMARY KEY (ORID)
);

CREATE TABLE ORIGIN_MEA_TRACE (
    ORID BIGINT,,
    CLUSTAID BIGINT,,
    ACTIVETIME_LOOKUP DOUBLE PRECISION,,
    BEST_REF_MATCH_ORID BIGINT,,
    APPLIED_THRESHOLD REAL,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_origin_mea_trace PRIMARY KEY (ORID)
);

CREATE TABLE ORIGIN_SDO (
    ORID BIGINT,,
    CONSTRAINT pk_origin_sdo PRIMARY KEY (ORID)
);

CREATE TABLE ORIGIN_TAG (
    ORID BIGINT,,
    PROCESS_MODE VARCHAR(32),,
    PROCESS_ATTRIBUTE VARCHAR(32),,
    NDEF SMALLINT,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_origin_tag PRIMARY KEY (ORID)
);

CREATE TABLE OUTAGE_STATION_DATA (
    OUTAGE_ID BIGINT,,
    STA VARCHAR(6),,
    START_DATE TIMESTAMP,,
    END_DATE TIMESTAMP,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE OUTAGE_STATION_RECEIVE (
    OUTAGE_ID BIGINT,,
    STA VARCHAR(6),,
    START_DATE TIMESTAMP,,
    END_DATE TIMESTAMP,,
    ENDTIME DOUBLE PRECISION,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE POLYGON (
    POLYID BIGINT,,
    REGION_NAME VARCHAR(30),,
    PERIMETERTYPE VARCHAR(8),,
    INSIDEFLAG VARCHAR(1),,
    OUTSIDEFLAG VARCHAR(1),,
    EDGEFLAG VARCHAR(1),,
    AUTH VARCHAR(15),,
    COMMENTS VARCHAR(4000),,
    LDDATE TIMESTAMP
);

CREATE TABLE POLYPOINT (
    POLYID BIGINT,,
    SEQUENCE BIGINT,,
    LAT DOUBLE PRECISION,,
    LON DOUBLE PRECISION,,
    LDDATE TIMESTAMP
);

CREATE TABLE PROCESSING_RECIPE (
    PROCID BIGINT,,
    PROCMETHOD VARCHAR(20),,
    IDNAME VARCHAR(15),,
    IDVALUE BIGINT,,
    PROCORDER INTEGER,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE PROCESS_TRACKING (
    TRACKINGID BIGINT,,
    PROCESS VARCHAR(256),,
    MACHINE VARCHAR(128),,
    SYS_AREA VARCHAR(128),,
    SYS_SITE VARCHAR(128),,
    PROC_START_DATE TIMESTAMP,,
    PROC_END_DATE TIMESTAMP,,
    STATE VARCHAR(16),,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE QCMASKDEF (
    QCDEFID BIGINT,,
    FIX SMALLINT,,
    NTAPER INTEGER,,
    DROP_THR INTEGER,,
    SINGLE_TRACE_SPIKE_THR DOUBLE PRECISION,,
    NITER INTEGER,,
    NSAMP INTEGER,,
    NOVER INTEGER,,
    SPIKE_THR DOUBLE PRECISION,,
    SPIKE_STAT INTEGER,,
    SPIKE_VAL DOUBLE PRECISION,,
    SPIKE_NPWIN INTEGER,,
    SPIKE_DSET INTEGER,,
    NOISE_THRESH DOUBLE PRECISION,,
    SPIKE_WINLEN INTEGER,,
    INTERQUAR_COEF DOUBLE PRECISION,,
    NOISE_NSAMP INTEGER,,
    NOISE_NOVERLAP INTEGER,,
    ALGORITHM_LIST VARCHAR(100),,
    ONDATE INTEGER,,
    OFFDATE INTEGER,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE QCMASKINFO (
    QCMASKID BIGINT,,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    TIME DOUBLE PRECISION,,
    ENDTIME DOUBLE PRECISION,,
    SAMPRATE REAL,,
    NSEG INTEGER,,
    QCDEFID BIGINT,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE QCMASKSEG (
    QCMASKID BIGINT,,
    STARTSAMPLE INTEGER,,
    ENDSAMPLE INTEGER,,
    MASKTYPE INTEGER,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE QSHELL_INTERVAL (
    QSHELL_INTVLID BIGINT,,
    INTVLID BIGINT,,
    CLASS VARCHAR(16),,
    NAME VARCHAR(20),,
    PROC_START_DATE TIMESTAMP,,
    PROC_END_DATE TIMESTAMP,,
    STATE VARCHAR(16),,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE RDA_PARAM (
    POLYID BIGINT,,
    RDA_VERID BIGINT,,
    GAMMA DOUBLE PRECISION,,
    LAMBDA DOUBLE PRECISION,,
    CLASS_DECISION_THRESH DOUBLE PRECISION,,
    AUTH VARCHAR(15),,
    COMMENTS VARCHAR(4000),,
    LDDATE TIMESTAMP
);

CREATE TABLE REG_RATIO_DISCRIM (
    POLYID BIGINT,,
    COV_VERID BIGINT,,
    NUMERATOR_PHASE VARCHAR(8),,
    DENOMINATOR_PHASE VARCHAR(8),,
    NUM_LOW_FREQ DOUBLE PRECISION,,
    NUM_HI_FREQ DOUBLE PRECISION,,
    DEN_LOW_FREQ DOUBLE PRECISION,,
    DEN_HI_FREQ DOUBLE PRECISION,,
    MEAN_EX_VAL DOUBLE PRECISION,,
    NUM_STATION_VAR DOUBLE PRECISION,,
    DEN_STATION_VAR DOUBLE PRECISION,,
    NUM_EVENT_VAR DOUBLE PRECISION,,
    DEN_EVENT_VAR DOUBLE PRECISION,,
    LDDATE TIMESTAMP
);

CREATE TABLE REMAP (
    SOURCE VARCHAR(512),,
    ID_NAME VARCHAR(12),,
    ORIGINAL_ID BIGINT,,
    CURRENT_ID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE REMARK (
    COMMID BIGINT,,
    LINENO INTEGER,,
    REMARK VARCHAR(160),,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_remark PRIMARY KEY (COMMID)
);

CREATE TABLE REMOVED_BEAM_DFILE (
    DFILE VARCHAR(32),,
    LDDATE TIMESTAMP
);

CREATE TABLE REQUEST (
    REQID BIGINT,,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    ARRAY VARCHAR(8),,
    ORID BIGINT,,
    EVID BIGINT,,
    TIME DOUBLE PRECISION,,
    ENDTIME DOUBLE PRECISION,,
    CLASS VARCHAR(16),,
    REQ_STATE VARCHAR(16),,
    STATECOUNT INTEGER,,
    COMPLETE INTEGER,,
    REQUESTOR VARCHAR(15),,
    MODTIME DOUBLE PRECISION,,
    MODAUTHOR VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE SADO_EMAIL_HISTORY (
    SADO_EMAIL_ID BIGINT,,
    REPORT_ID BIGINT,,
    SUBJECT VARCHAR(1000),,
    RECIPIENTS VARCHAR(4000),,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE SADO_PDF_REPORTS (
    SADO_PDF_REPORT_ID BIGINT,,
    REPORT_ID BIGINT,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE SADO_REPORT (
    REPORT_ID BIGINT,,
    EVID BIGINT,,
    ORID BIGINT,,
    GRN INTEGER,,
    EVENT_TIME DOUBLE PRECISION,,
    TITLE VARCHAR(64),,
    ANALYST VARCHAR(32),,
    ACCOUNT VARCHAR(15),,
    CLASSIFICATION VARCHAR(256),,
    TTGE VARCHAR(1),,
    SADO_RELEASED VARCHAR(1),,
    ALERT_MANAGER_CALLED VARCHAR(1),,
    EXERCISE VARCHAR(1),,
    EMAIL_TYPE VARCHAR(32),,
    ALERT_MANAGER VARCHAR(64),,
    YIELD_CALCULATOR_REGION_SELECT VARCHAR(64),,
    FINAL_DETERMINATION VARCHAR(32),,
    MAG_MAGTYPE VARCHAR(32),,
    OVERBURDEN_SET VARCHAR(1),,
    OVERBURDEN REAL,,
    COMMENTS VARCHAR(4000),,
    ECM_DETERMINATION VARCHAR(32),,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE SADO_REPORT_LANDMARKS (
    REPORT_LANDMARKS_ID BIGINT,,
    REPORT_ID BIGINT,,
    LOCATION_ID BIGINT,,
    TESTSITE VARCHAR(1),,
    NAME VARCHAR(64),,
    LAT REAL,,
    LON REAL,,
    DISTANCE REAL,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE SADO_SCREENSHOTS (
    SADO_SCREENSHOT_ID BIGINT,,
    REPORT_ID BIGINT,,
    TYPE VARCHAR(10),,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE SADO_STATE (
    SADO_STATE_ID BIGINT,,
    REPORT_ID BIGINT,,
    SADO_STATE_CATEGORY_ID BIGINT,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE SADO_STATE_CATEGORIES (
    SADO_STATE_CATEGORY_ID BIGINT,,
    TITLE VARCHAR(64),,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE SADO_USERS (
    SADO_USERS_ID BIGINT,,
    SADO_NAME VARCHAR(64),,
    OFFICE_SYMBOL VARCHAR(64),,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE SENSOR (
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    TIME DOUBLE PRECISION,,
    ENDTIME DOUBLE PRECISION,,
    INID BIGINT,,
    CHANID BIGINT,,
    JDATE INTEGER,,
    CALRATIO REAL,,
    CALPER REAL,,
    TSHIFT REAL,,
    INSTANT VARCHAR(1),,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_sensor PRIMARY KEY (STA, CHAN, TIME, ENDTIME)
);

CREATE TABLE SITE (
    STA VARCHAR(6),,
    ONDATE INTEGER,,
    OFFDATE INTEGER,,
    LAT DOUBLE PRECISION,,
    LON DOUBLE PRECISION,,
    ELEV REAL,,
    STANAME VARCHAR(50),,
    STATYPE VARCHAR(4),,
    REFSTA VARCHAR(6),,
    DNORTH REAL,,
    DEAST REAL,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_site PRIMARY KEY (STA, ONDATE)
);

CREATE TABLE SITEAUX (
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    TIME DOUBLE PRECISION,,
    NOIS REAL,,
    NOISSD REAL,,
    AMCOR REAL,,
    AMCORSD REAL,,
    SNTHRSH REAL,,
    RELY REAL,,
    PTMCOR REAL,,
    STMCOR REAL,,
    STAPER REAL,,
    DELK REAL,,
    DELS REAL,,
    AUTH VARCHAR(15),,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE SITECHAN (
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    ONDATE INTEGER,,
    CHANID BIGINT,,
    OFFDATE INTEGER,,
    CTYPE VARCHAR(4),,
    EDEPTH REAL,,
    HANG REAL,,
    VANG REAL,,
    DESCRIP VARCHAR(50),,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_sitechan PRIMARY KEY (STA, CHAN, ONDATE)
);

CREATE TABLE SNR_PHASE (
    POLYID BIGINT,,
    AMPCOR_VERID BIGINT,,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    PHASE VARCHAR(8),,
    MIN_NUM_ELEM SMALLINT,,
    SNR_THRESH DOUBLE PRECISION,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE SREGION (
    SRN INTEGER,,
    SRNAME VARCHAR(40),,
    LDDATE TIMESTAMP
);

CREATE TABLE STAMAG (
    MAGID BIGINT,,
    AMPID BIGINT,,
    STA VARCHAR(6),,
    ARID BIGINT,,
    ORID BIGINT,,
    EVID BIGINT,,
    PHASE VARCHAR(8),,
    DELTA REAL,,
    MAGTYPE VARCHAR(6),,
    MAGNITUDE REAL,,
    UNCERTAINTY REAL,,
    MAGRES REAL,,
    MAGDEF VARCHAR(1),,
    MMODEL VARCHAR(15),,
    AUTH VARCHAR(15),,
    COMMID BIGINT,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_stamag PRIMARY KEY (MAGID)
);

CREATE TABLE STANET (
    NET VARCHAR(8),,
    STA VARCHAR(6),,
    TIME DOUBLE PRECISION,,
    ENDTIME DOUBLE PRECISION,,
    LDDATE TIMESTAMP
);

CREATE TABLE STAQUAL_DNAMES (
    ID BIGINT,,
    STA VARCHAR(6),,
    DNAME VARCHAR(8),,
    ON_TIME DOUBLE PRECISION,,
    OFF_TIME DOUBLE PRECISION,,
    AUTHOR VARCHAR(64),,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE STATION_PROCESSING (
    CLUSTAID BIGINT,,
    ACTIVETIME DOUBLE PRECISION,,
    PROCID BIGINT,,
    PROCTYPE VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE STATION_QUALITY (
    SQID BIGINT,,
    STA VARCHAR(6),,
    DNAME VARCHAR(8),,
    TIME DOUBLE PRECISION,,
    ENDTIME DOUBLE PRECISION,,
    JDATE INTEGER,,
    AVGCHANS REAL,,
    EXPECTED DOUBLE PRECISION,,
    RETRIEVED DOUBLE PRECISION,,
    MASKED DOUBLE PRECISION,,
    MASKS INTEGER,,
    NDET_THRES REAL,,
    AZIMUTH REAL,,
    SLOW REAL,,
    NOISE REAL,,
    NOISEDEV REAL,,
    NOISETYPE VARCHAR(10),,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE STAYIELD (
    YIELDID BIGINT,,
    AMPID BIGINT,,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    ORID BIGINT,,
    ARID BIGINT,,
    YIELD REAL,,
    FFACTOR REAL,,
    WMODEL_NAME VARCHAR(50),,
    AUTH VARCHAR(15),,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE STA_CODA_SPECTRUM (
    AMPID BIGINT,,
    FREQ REAL,,
    AMPCOR REAL,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE SVDDISC (
    LSVID BIGINT,,
    CLUSTAID BIGINT,,
    ACTIVETIME DOUBLE PRECISION,,
    STA VARCHAR(6),,
    NSAMP INTEGER,,
    SAMPRATE REAL,,
    SINGULAR_VALUE REAL,,
    UNITS VARCHAR(1),,
    DIR VARCHAR(64),,
    DFILE VARCHAR(32),,
    FOFF BIGINT,,
    COMMID BIGINT,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE SVDDISC_CHAN_ORDER (
    CLUSTAID BIGINT,,
    STA VARCHAR(6),,
    CHAN VARCHAR(6),,
    ACTIVETIME DOUBLE PRECISION,,
    SORT_ORDER INTEGER
);

CREATE TABLE TAPER (
    TAPERID BIGINT,,
    TAPER_TYPE VARCHAR(16),,
    TAPER_PERCT REAL,,
    TAPER_MAXPTS INTEGER,,
    TAPER_MINPTS INTEGER,,
    AUTH VARCHAR(15),,
    LDDATE TIMESTAMP
);

CREATE TABLE TIMESTAMP (
    PROCCLASS VARCHAR(16),,
    PROCNAME VARCHAR(16),,
    TIME DOUBLE PRECISION,,
    LDDATE TIMESTAMP
);

CREATE TABLE TOMO_INFO (
    TOMOID BIGINT,,
    MINLAT REAL,,
    MAXLAT REAL,,
    DLAT REAL,,
    MINLON REAL,,
    MAXLON REAL,,
    DLON REAL,,
    DIR VARCHAR(64),,
    DFILE VARCHAR(32),,
    AUTH VARCHAR(15),,
    DESCRIP VARCHAR(50),,
    LDDATE TIMESTAMP
);

CREATE TABLE USER_FILTER (
    OSUSER VARCHAR(30),,
    SEQ INTEGER,,
    FILTER_STRING VARCHAR(1024),,
    FILTERID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE USER_PRIVILEGES (
    AUTH VARCHAR(15),,
    MAX_DURATION INTEGER,,
    APP_TABLE VARCHAR(32),,
    LDDATE TIMESTAMP
);

CREATE TABLE WFACTIVITY (
    CLASS VARCHAR(16),,
    NAME VARCHAR(20),,
    TIME DOUBLE PRECISION,,
    DURATION REAL,,
    MIN_TIME DOUBLE PRECISION,,
    MAX_ENDTIME NUMERIC,,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE WFAUDIT (
    WFAUDITID BIGINT,,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    OLD_TIME DOUBLE PRECISION,,
    NEW_TIME DOUBLE PRECISION,,
    OLD_ENDTIME DOUBLE PRECISION,,
    NEW_ENDTIME DOUBLE PRECISION,,
    MODDATE TIMESTAMP
);

CREATE TABLE WFCONV (
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    CHANID BIGINT,,
    INAUTH VARCHAR(1),,
    INCOMP VARCHAR(2),,
    INTYPE VARCHAR(2),,
    INSAMP INTEGER,,
    OUTAUTH VARCHAR(1),,
    OUTCOMP VARCHAR(2),,
    OUTTYPE VARCHAR(2),,
    OUTSAMP INTEGER,,
    STRIP VARCHAR(1),,
    COMMID BIGINT,,
    LDDATE TIMESTAMP
);

CREATE TABLE WFDISC (
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    TIME DOUBLE PRECISION,,
    WFID BIGINT,,
    CHANID BIGINT,,
    JDATE INTEGER,,
    ENDTIME DOUBLE PRECISION,,
    NSAMP INTEGER,,
    SAMPRATE REAL,,
    CALIB REAL,,
    CALPER REAL,,
    INSTYPE VARCHAR(6),,
    SEGTYPE VARCHAR(1),,
    DATATYPE VARCHAR(2),,
    CLIP VARCHAR(1),,
    DIR VARCHAR(64),,
    DFILE VARCHAR(32),,
    FOFF BIGINT,,
    COMMID BIGINT,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_wfdisc PRIMARY KEY (WFID)
);

CREATE TABLE WFFILE (
    WFFID BIGINT,,
    DIR VARCHAR(64),,
    DFILE VARCHAR(32),,
    MACHINE VARCHAR(32),,
    LOCAL_DIR VARCHAR(64),,
    TLEN REAL,,
    TIME DOUBLE PRECISION,,
    REAPTIME DOUBLE PRECISION,,
    STA VARCHAR(6),,
    CHAN VARCHAR(8),,
    SAMPRATE REAL,,
    CHANID BIGINT,,
    WFMID BIGINT,,
    MODDATE TIMESTAMP,,
    LDDATE TIMESTAMP
);

CREATE TABLE WFTAG (
    TAGNAME VARCHAR(8),,
    TAGID BIGINT,,
    WFID BIGINT,,
    LDDATE TIMESTAMP,,
    CONSTRAINT pk_wftag PRIMARY KEY (TAGID, WFID)
);

CREATE TABLE XTAG (
    THISID BIGINT,,
    THATID BIGINT,,
    THISNAME VARCHAR(8),,
    THATNAME VARCHAR(8),,
    THISDB VARCHAR(32),,
    THATDB VARCHAR(32),,
    LDDATE TIMESTAMP
);

