-- USNDC Schema Deployment Batch 8
-- Tables in this batch: 20

CREATE TABLE SENSOR (
    STA VARCHAR(6)
    CHAN VARCHAR(8)
    TIME DOUBLE PRECISION
    ENDTIME DOUBLE PRECISION
    INID BIGINT
    CHANID BIGINT
    JDATE INTEGER
    CALRATIO REAL
    CALPER REAL
    TSHIFT REAL
    INSTANT VARCHAR(1)
    LDDATE TIMESTAMP
    CONSTRAINT pk_sensor PRIMARY KEY (STA, CHAN, TIME, ENDTIME)
);

CREATE TABLE SITE (
    STA VARCHAR(6)
    ONDATE INTEGER
    OFFDATE INTEGER
    LAT DOUBLE PRECISION
    LON DOUBLE PRECISION
    ELEV REAL
    STANAME VARCHAR(50)
    STATYPE VARCHAR(4)
    REFSTA VARCHAR(6)
    DNORTH REAL
    DEAST REAL
    LDDATE TIMESTAMP
    CONSTRAINT pk_site PRIMARY KEY (STA, ONDATE)
);

CREATE TABLE SITEAUX (
    STA VARCHAR(6)
    CHAN VARCHAR(8)
    TIME DOUBLE PRECISION
    NOIS REAL
    NOISSD REAL
    AMCOR REAL
    AMCORSD REAL
    SNTHRSH REAL
    RELY REAL
    PTMCOR REAL
    STMCOR REAL
    STAPER REAL
    DELK REAL
    DELS REAL
    AUTH VARCHAR(15)
    COMMID BIGINT
    LDDATE TIMESTAMP
);

CREATE TABLE SITECHAN (
    STA VARCHAR(6)
    CHAN VARCHAR(8)
    ONDATE INTEGER
    CHANID BIGINT
    OFFDATE INTEGER
    CTYPE VARCHAR(4)
    EDEPTH REAL
    HANG REAL
    VANG REAL
    DESCRIP VARCHAR(50)
    LDDATE TIMESTAMP
    CONSTRAINT pk_sitechan PRIMARY KEY (STA, CHAN, ONDATE)
);

CREATE TABLE SNR_PHASE (
    POLYID BIGINT
    AMPCOR_VERID BIGINT
    STA VARCHAR(6)
    CHAN VARCHAR(8)
    PHASE VARCHAR(8)
    MIN_NUM_ELEM SMALLINT
    SNR_THRESH DOUBLE PRECISION
    AUTH VARCHAR(15)
    LDDATE TIMESTAMP
);

CREATE TABLE SREGION (
    SRN INTEGER
    SRNAME VARCHAR(40)
    LDDATE TIMESTAMP
);

CREATE TABLE STAMAG (
    MAGID BIGINT
    AMPID BIGINT
    STA VARCHAR(6)
    ARID BIGINT
    ORID BIGINT
    EVID BIGINT
    PHASE VARCHAR(8)
    DELTA REAL
    MAGTYPE VARCHAR(6)
    MAGNITUDE REAL
    UNCERTAINTY REAL
    MAGRES REAL
    MAGDEF VARCHAR(1)
    MMODEL VARCHAR(15)
    AUTH VARCHAR(15)
    COMMID BIGINT
    LDDATE TIMESTAMP
    CONSTRAINT pk_stamag PRIMARY KEY (MAGID)
);

CREATE TABLE STANET (
    NET VARCHAR(8)
    STA VARCHAR(6)
    TIME DOUBLE PRECISION
    ENDTIME DOUBLE PRECISION
    LDDATE TIMESTAMP
);

CREATE TABLE STAQUAL_DNAMES (
    ID BIGINT
    STA VARCHAR(6)
    DNAME VARCHAR(8)
    ON_TIME DOUBLE PRECISION
    OFF_TIME DOUBLE PRECISION
    AUTHOR VARCHAR(64)
    MODDATE TIMESTAMP
    LDDATE TIMESTAMP
);

CREATE TABLE STATION_PROCESSING (
    CLUSTAID BIGINT
    ACTIVETIME DOUBLE PRECISION
    PROCID BIGINT
    PROCTYPE VARCHAR(15)
    LDDATE TIMESTAMP
);

CREATE TABLE STAYIELD (
    YIELDID BIGINT
    AMPID BIGINT
    STA VARCHAR(6)
    CHAN VARCHAR(8)
    ORID BIGINT
    ARID BIGINT
    YIELD REAL
    FFACTOR REAL
    WMODEL_NAME VARCHAR(50)
    AUTH VARCHAR(15)
    COMMID BIGINT
    LDDATE TIMESTAMP
);

CREATE TABLE STA_CODA_SPECTRUM (
    AMPID BIGINT
    FREQ REAL
    AMPCOR REAL
    AUTH VARCHAR(15)
    LDDATE TIMESTAMP
);

CREATE TABLE SVDDISC (
    LSVID BIGINT
    CLUSTAID BIGINT
    ACTIVETIME DOUBLE PRECISION
    STA VARCHAR(6)
    NSAMP INTEGER
    SAMPRATE REAL
    SINGULAR_VALUE REAL
    UNITS VARCHAR(1)
    DIR VARCHAR(64)
    DFILE VARCHAR(32)
    FOFF BIGINT
    COMMID BIGINT
    AUTH VARCHAR(15)
    LDDATE TIMESTAMP
);

CREATE TABLE SVDDISC_CHAN_ORDER (
    CLUSTAID BIGINT
    STA VARCHAR(6)
    CHAN VARCHAR(6)
    ACTIVETIME DOUBLE PRECISION
    SORT_ORDER INTEGER
);

CREATE TABLE TAPER (
    TAPERID BIGINT
    TAPER_TYPE VARCHAR(16)
    TAPER_PERCT REAL
    TAPER_MAXPTS INTEGER
    TAPER_MINPTS INTEGER
    AUTH VARCHAR(15)
    LDDATE TIMESTAMP
);

CREATE TABLE TIMESTAMP (
    PROCCLASS VARCHAR(16)
    PROCNAME VARCHAR(16)
    TIME DOUBLE PRECISION
    LDDATE TIMESTAMP
);

CREATE TABLE TOMO_INFO (
    TOMOID BIGINT
    MINLAT REAL
    MAXLAT REAL
    DLAT REAL
    MINLON REAL
    MAXLON REAL
    DLON REAL
    DIR VARCHAR(64)
    DFILE VARCHAR(32)
    AUTH VARCHAR(15)
    DESCRIP VARCHAR(50)
    LDDATE TIMESTAMP
);

CREATE TABLE USER_FILTER (
    OSUSER VARCHAR(30)
    SEQ INTEGER
    FILTER_STRING VARCHAR(1024)
    FILTERID BIGINT
    LDDATE TIMESTAMP
);

CREATE TABLE USER_PRIVILEGES (
    AUTH VARCHAR(15)
    MAX_DURATION INTEGER
    APP_TABLE VARCHAR(32)
    LDDATE TIMESTAMP
);

CREATE TABLE WFACTIVITY (
    CLASS VARCHAR(16)
    NAME VARCHAR(20)
    TIME DOUBLE PRECISION
    DURATION REAL
    MIN_TIME DOUBLE PRECISION
    MAX_ENDTIME NUMERIC
    MODDATE TIMESTAMP
    LDDATE TIMESTAMP
);

