-- USNDC Schema Deployment Batch 5
-- Tables in this batch: 20

CREATE TABLE FILTER_VALUES_DOUBLE (
    FILTERID BIGINT
    VALUE_NAME VARCHAR(48)
    D_VALUE DOUBLE PRECISION
    LDDATE TIMESTAMP
);

CREATE TABLE FILTER_VALUES_INTEGER (
    FILTERID BIGINT
    VALUE_NAME VARCHAR(48)
    I_VALUE BIGINT
    LDDATE TIMESTAMP
);

CREATE TABLE FILTER_VALUES_STRING (
    FILTERID BIGINT
    VALUE_NAME VARCHAR(48)
    S_VALUE VARCHAR(1024)
    LDDATE TIMESTAMP
);

CREATE TABLE FK_PROCESSING (
    ARID BIGINT
    PROCID BIGINT
    LEAD REAL
    LAG REAL
    FKFHI REAL
    FKFLO REAL
    AUTH VARCHAR(15)
    LDDATE TIMESTAMP
);

CREATE TABLE FTPFAILED (
    MSGID BIGINT
    FTP_ADDRESS VARCHAR(64)
    NUMFAILEDATTEMPT SMALLINT
    LASTFAILEDTIME DOUBLE PRECISION
    FTPSTATUS VARCHAR(8)
    LDDATE TIMESTAMP
);

CREATE TABLE FTPLOGIN (
    FTP_ADDRESS VARCHAR(64)
    USERNAME VARCHAR(24)
    PASSWORD VARCHAR(16)
    LDDATE TIMESTAMP
);

CREATE TABLE GA_TAG (
    OBJTYPE VARCHAR(1)
    ID BIGINT
    PROCESS_STATE VARCHAR(20)
    LAT REAL
    LON REAL
    TIME DOUBLE PRECISION
    EVID_REJECT BIGINT
    AUTH VARCHAR(15)
    LDDATE TIMESTAMP
);

CREATE TABLE GREGION (
    GRN INTEGER
    GRNAME VARCHAR(40)
    LDDATE TIMESTAMP
);

CREATE TABLE HISTORIC_INFO_CYLINDER (
    HISTORIC_INFO_CYLINDER_ID BIGINT
    LAT DOUBLE PRECISION
    LON DOUBLE PRECISION
    RADIUS REAL
    DEPTH REAL
    LOWER_DEPTH REAL
    UPPER_DEPTH REAL
    AUTHOR VARCHAR(64)
    MODDATE TIMESTAMP
    LDDATE TIMESTAMP
);

CREATE TABLE HISTORIC_INFO_SHELL (
    HISTORIC_INFO_SHELL_ID BIGINT
    ALGORITHM_ID BIGINT
    LAT DOUBLE PRECISION
    LON DOUBLE PRECISION
    INNER_RADIUS REAL
    OUTER_RADIUS REAL
    DEPTH REAL
    LOWER_DEPTH REAL
    UPPER_DEPTH REAL
    MIN_AZIMUTH REAL
    MAX_AZIMUTH REAL
    REFSTA VARCHAR(6)
    PHASE VARCHAR(8)
    THRESHOLD REAL
    UNCERTAINTY REAL
    RELIABILITY REAL
    NUM_OBSERVATIONS INTEGER
    PROCESSING_MODE SMALLINT
    ON_DATE TIMESTAMP
    OFF_DATE TIMESTAMP
    AUTHOR VARCHAR(64)
    MODDATE TIMESTAMP
    LDDATE TIMESTAMP
);

CREATE TABLE HISTORIC_INFO_STA_PHASE (
    HISTORIC_INFO_STA_PHASE_ID BIGINT
    HISTORIC_INFO_CYLINDER_ID BIGINT
    ALGORITHM_ID BIGINT
    REFSTA VARCHAR(6)
    PHASE VARCHAR(8)
    THRESHOLD REAL
    UNCERTAINTY REAL
    RELIABILITY REAL
    NUM_OBSERVATIONS INTEGER
    PROCESSING_MODE SMALLINT
    ON_DATE TIMESTAMP
    OFF_DATE TIMESTAMP
    AUTHOR VARCHAR(64)
    MODDATE TIMESTAMP
    LDDATE TIMESTAMP
);

CREATE TABLE HYDRO_ARRIVAL (
    ARID BIGINT
    STA VARCHAR(6)
    DURONSET DOUBLE PRECISION
    DUREND DOUBLE PRECISION
    ONSET_TIME DOUBLE PRECISION
    TERMINATION_TIME DOUBLE PRECISION
    CPLAG REAL
    BPFRQAC REAL
    RT REAL
    BPFRQCEP REAL
    RMS REAL
    FLT_RTO REAL
    NORMAMP REAL
    AMPCORCLIP REAL
    AMPCORDIST REAL
    AMPCORDEPTH REAL
    YIELD REAL
    YLDERR REAL
    COMMID BIGINT
    LDDATE TIMESTAMP
);

CREATE TABLE HYDRO_ARR_GROUP (
    HYDRO_ID BIGINT
    AZ1 REAL
    AZ2 REAL
    SLOW REAL
    DELAZ REAL
    NHYDARR SMALLINT
    NET VARCHAR(8)
    HYD_GRP_PHASE VARCHAR(8)
    LDDATE TIMESTAMP
);

CREATE TABLE HYDRO_ASSOC (
    ARID BIGINT
    HYDRO_ID BIGINT
    AZCONTRIB VARCHAR(1)
    LDDATE TIMESTAMP
);

CREATE TABLE HYDRO_ORIGIN (
    ORID BIGINT
    HYDROLOC_CODE INTEGER
    HYDROYIELD REAL
    HYDROYLDERR REAL
    NUM_IN_SERIES INTEGER
    SERID BIGINT
    HYD_CLASS_CODE INTEGER
    COMMID BIGINT
    LDDATE TIMESTAMP
);

CREATE TABLE INSTRUMENT (
    INID BIGINT
    INSNAME VARCHAR(50)
    INSTYPE VARCHAR(6)
    BAND VARCHAR(1)
    DIGITAL VARCHAR(1)
    SAMPRATE REAL
    NCALIB REAL
    NCALPER REAL
    DIR VARCHAR(64)
    DFILE VARCHAR(32)
    RSPTYPE VARCHAR(6)
    LDDATE TIMESTAMP
    CONSTRAINT pk_instrument PRIMARY KEY (INID)
);

CREATE TABLE INTERVAL (
    INTVLID BIGINT
    CLASS VARCHAR(16)
    NAME VARCHAR(20)
    TIME DOUBLE PRECISION
    ENDTIME DOUBLE PRECISION
    STATE VARCHAR(16)
    AUTH VARCHAR(15)
    PERCENT_AVAILABLE DOUBLE PRECISION
    PROC_START_DATE TIMESTAMP
    PROC_END_DATE TIMESTAMP
    MODDATE TIMESTAMP
    COMMID BIGINT
    LDDATE TIMESTAMP
);

CREATE TABLE MDAC_FD (
    FDID BIGINT
    AMPCOR_VERID BIGINT
    CORRID BIGINT
    LFREQ REAL
    STA VARCHAR(6)
    CHAN VARCHAR(8)
    TOMOID BIGINT
    POLYID BIGINT
    A DOUBLE PRECISION
    B DOUBLE PRECISION
    C DOUBLE PRECISION
    SITEFACT DOUBLE PRECISION
    ALGOID BIGINT
    AUTH VARCHAR(15)
    LDDATE TIMESTAMP
);

CREATE TABLE MDAC_FI (
    CORRID BIGINT
    AMPCOR_VERID BIGINT
    POLYID BIGINT
    STA VARCHAR(6)
    PHASE VARCHAR(8)
    CHAN VARCHAR(8)
    CORRNAME VARCHAR(32)
    SIGMA DOUBLE PRECISION
    DELSIGMA DOUBLE PRECISION
    PSI REAL
    DELPSI REAL
    Q0 DOUBLE PRECISION
    DELQ0 DOUBLE PRECISION
    GAMMA REAL
    DELGAMMA REAL
    ZETA REAL
    M0_REF DOUBLE PRECISION
    U0 REAL
    ETA REAL
    DELETA REAL
    DISTCRIT DOUBLE PRECISION
    ALPHAS REAL
    BETAS REAL
    RHOS DOUBLE PRECISION
    ALPHAR REAL
    BETAR REAL
    RHOR DOUBLE PRECISION
    RADPATP REAL
    RADPATS REAL
    SNR1 DOUBLE PRECISION
    SNR2 DOUBLE PRECISION
    NOISETYPE VARCHAR(15)
    MAGID BIGINT
    MAGTYPE VARCHAR(6)
    ALGOID BIGINT
    AUTH VARCHAR(15)
    LDDATE TIMESTAMP
);

CREATE TABLE MSGAUX (
    MSGID BIGINT
    MSGROW SMALLINT
    STATECOUNT INTEGER
    COMMAND VARCHAR(24)
    SUB_STATUS VARCHAR(24)
    LDDATE TIMESTAMP
);

