-- USNDC Schema - Tables Only (Manual Clean Version)
-- Drop existing tables first
DROP TABLE IF EXISTS ACTIVE_ID CASCADE;
DROP TABLE IF EXISTS AFFILIATION CASCADE;
DROP TABLE IF EXISTS ALGORITHM CASCADE;

-- Create tables without foreign key constraints
CREATE TABLE ACTIVE_ID (
    TAGNAME VARCHAR(8),
    TAGID BIGINT,
    CLIENT_INFO VARCHAR(64),
    AUTHOR VARCHAR(64),
    MODDATE TIMESTAMP,
    LDDATE TIMESTAMP
);

CREATE TABLE AFFILIATION (
    NET VARCHAR(8),
    STA VARCHAR(6),
    TIME DOUBLE PRECISION,
    ENDTIME DOUBLE PRECISION,
    LDDATE TIMESTAMP,
    CONSTRAINT pk_affiliation PRIMARY KEY (NET, STA, TIME)
);

CREATE TABLE ALGORITHM (
    ALGORITHM_ID BIGINT,
    ALGORITHM_NAME VARCHAR(64),
    DESCRIPTION VARCHAR(4000),
    ON_DATE TIMESTAMP,
    OFF_DATE TIMESTAMP,
    AUTHOR VARCHAR(64),
    MODDATE TIMESTAMP,
    LDDATE TIMESTAMP,
    CONSTRAINT pk_algorithm PRIMARY KEY (ALGORITHM_ID)
);